### ISSUE TITLE
Feature Request: sct_deepseg_lesion - output optional json file to allow for bids-compliant processing?

### ISSUE THREAD

**Issue by jqmcginnis** [spinalcordtoolbox/spinalcordtoolbox#4023] opened 2023-02-01 14:37 UTC
**Feature justification: Is your feature request related to a problem? Please describe.**
When using `sct_deepseg_lesion` on a cohort, I have noticed that we do not have the option of exporting a json file, accompanying the lesion segmentation, that specifies details w.r.t. how the lesion segmentation has been obtained.

For example, if we have a cohort with manual lesion segmentation files, i.e.

```
derivatives/labels/sub-m123456/ses-20230101/sub-m123456_session-20230101_lesion-manual.nii.gz
derivatives/labels/sub-m123456/ses-20230101/sub-m123456_session-20230101_lesion-manual.json
```
Wouldn't it be nice to have the possibility of outputing the sidecar json as well, when running `sct_deepseg_lesion`, e.g. obtaining:

```
derivatives/labels/sub-m123456/ses-20230101/sub-m123456_session-20230101_lesion-processed.nii.gz
derivatives/labels/sub-m123456/ses-20230101/sub-m123456_session-20230101_lesion-processed.json
```

That would promote, both the usage of BIDS, and at the same time would allow to infer users which version and settings (e.g. which particular classifier or contrasts were used) in the json.

**Describe the solution you'd like**
A command line, e.g. `-output_json`, to allow simultaneously generating a sidecar json with information regarding the process of the lesion segmentation.

**Describe alternatives you've considered**
Creating the sidecar json by myself.

However, I am unsure if this idea introduces a level of BIDS into sct that deviates from the other modules, and perhaps - by design choice - is not or should not be included. Happy to hear your ideas :slightly_smiling_face:

**Comment by jcohenadad** [comment] 2023-02-01 14:54
I don't think it's a bad idea to slowly introduce BIDS-compliant features in our SCT outputs. This is the way to converge to an official [BIDS App](https://bids-apps.neuroimaging.io/).

**Comment by joshuacwnewton** [comment] 2023-02-01 15:45
This is a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3394! But with a second request of this feature, perhaps we can increase priority of that issue. :blush:

**Closed by joshuacwnewton** 2023-02-01 15:45 UTC

**Comment by joshuacwnewton** [comment] 2023-02-01 15:49
> This is the way to converge to an official [BIDS App](https://bids-apps.neuroimaging.io/).

Related issue:

- #3344
