### ISSUE TITLE
WSL segfault

### ISSUE THREAD

**Issue by kousu** [spinalcordtoolbox/spinalcordtoolbox#3308] opened 2021-03-22 04:04 UTC
Reported at https://forum.spinalcordmri.org/t/segmentation-fault-core-dumped/660/: something is causing a segfault when running

```
sct_maths -i [linmin.nii.gz](https://osf.io/download/uxtm6) -mean t -o dmri_mean.nii.gz
```

**Comment by kousu** [comment] 2021-03-22 04:27
There is so far very little to go on here. My best clue is that this is WSL (which we don't test very thoroughly), which you can see in the OS line:

> OS: linux (Linux-4.4.0-19041-Microsoft-x86_64-with-debian-buster-sid)

I tried to reproduce it with WSL (and in the process make such reproductions themselves more reliable: https://github.com/neuropoly/internal_tools/issues/14 -- still working on this) but failed, like jcohenadad did on macOS.

I noticed that the Debian Microsoft provides at https://aka.ms/wsl-debian-gnulinux is not the one listed by the user. When I [tried to repro](https://showterm.io/c82a348d19d20ecd23e88#4429) I got:

> OS: linux (Linux-4.4.0-18362-Microsoft-x86_64-with-debian-10.8)

Also their's said:

>   Using bundled python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01)
> [GCC 9.3.0] at /home/forest/sct/python/envs/venv_sct/bin/python

but mine said

>  Using bundled python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04)                                                           
> [GCC 7.3.0] at /home/user/sct/python/envs/venv_sct/bin/python                                            

which is..weird isn't it? If they installed sct using our installer shouldn't they be using anaconda python? Not conda-forge python? Maybe they're hitting this bug: https://github.com/neuropoly/spinalcordtoolbox/issues/3029. But we fixed that, didn't we? Plus the path is right: `/home/forest/sct/python/`.


So I don't know how they got '-buster-sid' there. Or actually why it would say "buster-sid". A key point is that "sid" is Debian's synonym for "testing"; and also, unlike the rest of Debian, it's a rolling-release distro. According to https://www.debian.org/releases/ 'buster' was 'sid' a while ago, but now 'bullseye' == 'sid', so I don't know what 'buster-sid' is supposed to mean; maybe their system is both stuck in the past and the future at the same time?

In their `history` you can see:

```
   19  sudo cp /etc/apt/sources.list /etc/apt/sources.list.20210305
   20  sudo vim sources.list
```

So I suspect they followed a [guide like this](https://davidsmith.is/2019/07/11/updating-your-wsl-debian-image-to-buster/) to upgrade their WSL image to a newer one, but that they did that months ago. Plus they don't seem to have ever run `apt-get dist-upgrade`, just `apt-get upgrade` which doesn't do the same thing (*shakes fist at apt*). So I bet they have some unusual mixture of libraries that's not helping things.

Still a segfault is a segfault and if there's a way to segfault our code it means there's probably a bug. Just because the particular versions we test against don't crash doesn't mean there's not a problem lurking. Maybe this user is a canary, testing newer libraries than we test against, and we should thank them for the early warning.

**Comment by kousu** [comment] 2021-03-22 04:29
The entire other avenue is: they reported the segfault went away by changing some file permissions: https://forum.spinalcordmri.org/t/segmentation-fault-core-dumped/660/14. Which just makes very little sense to me but I've seen stranger things.

I'm hoping to get some more details from them tomorrow.

**Comment by kousu** [comment] 2021-03-22 04:37
I'm also upgrading Windows to match them. But the only one available to me is [19042](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_20H2_(October_2020_Update)) not 19041; hopefully that's close enough:

![2021-03-22-000021_679x358_scrot](https://user-images.githubusercontent.com/987487/111941108-b3c26d80-8aa6-11eb-8ed5-767b516fb18e.png)

**Comment by joshuacwnewton** [comment] 2021-05-07 00:12
Since the issue is solved on the user end of things, and because this is a hard-to-pin-down isolated incident, do you think we could close this issue for now, @kousu ?

**Closed** 2021-05-07 14:26 UTC
Labels: bug, sct_maths
