### ISSUE TITLE
Angle correction is inconsistent when running `sct_process_segmentation` across GM/WM/SC segmentations

### ISSUE THREAD

**Issue by BFCombes** [spinalcordtoolbox/spinalcordtoolbox#4367] opened 2024-02-12 16:41 UTC
Dear all,

I am currently analysing mouse spinal cord areas in different segments and extracting values from the sct_process_segmentation function as described here: https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/issues/45

However, the sum of the GM and WM is not equivalent to the area of the total spinal cord (called sc in the _Metrics measurement based on model output #45_ mentioned above).

Does someone has an idea for this issue?

Thank you very much in advance for your time and help,
Kind regards,
Benjamin F. Combes

**Comment by joshuacwnewton** [comment] 2024-02-12 16:59
Thank you so much for opening this issue! 

> I am currently analysing mouse spinal cord areas in different segments and extracting values from the sct_process_segmentation function as described here: [ivadomed/model_seg_mouse-sc_wm-gm_t1#45](https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1/issues/45)

Just to quote the relevant commands from the issue you linked above:

> Divide the image in two files, one for GM and one for WM (plus SC):
> 
> ```bash
> # WM
> sct_maths -i ~/file_pred.nii.gz -bin 1 -o ~/file_pred_WM.nii.gz
> # GM (need to do it twice because WM value is 2)
> sct_maths -i ~/file_pred.nii.gz -sub ~/file_pred_WM.nii.gz -o ~/file_pred_GM.nii.gz
> sct_maths -i ~/file_pred_GM.nii.gz -sub ~/file_pred_WM.nii.gz -o ~/file_pred_GM.nii.gz
> # SC
> sct_maths -i ~/file_pred.nii.gz -bin 0.5 -o ~/file_pred_sc.nii.gz
> ```
>
> Compute area:
>
> ```bash
> # WM
> sct_process_segmentation -i ~/file_pred_WM.nii.gz -o ~/output_wm_area.csv -perslice 1
> # GM
> sct_process_segmentation -i ~/file_pred_GM.nii.gz -o ~/output_gm_area.csv -perslice 1
> # SC
> sct_process_segmentation -i ~/file_pred_sc.nii.gz -o ~/output_sc_area.csv -perslice 1
> ```

@plbenveniste has already provided me with a sample mouse file privately (see https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4345#discussion_r1484775345), so I will try to debug the issue on my end, and determine whether the issue is with `sct_maths` or if it is with `sct_process_segmentation`. :)

**Comment by BFCombes** [comment] 2024-02-12 17:06
Dear [joshuacwnewton](https://github.com/joshuacwnewton),

Exactly! Thank you very much for your help.
Please let me know if you need any files.

Benjamin

**Comment by joshuacwnewton** [comment] 2024-02-13 20:49
I tried running the segmentation using the newly merged `sct_deepseg` mouse model from #4345, which automatically splits the image into GM/WM based on the following logic (removing the need for subtraction):

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/fed99bc1ae345ffc6fc2cbc2cf143bac6b25f371/spinalcordtoolbox/deepseg/inference.py#L258-L266

To create the SC mask, I summed the two output images using:

```bash
sct_maths -i t1_mouse_GM_seg.nii.gz -add t1_mouse_WM_seg.nii.gz -o t1_mouse_SC_seg.nii.gz
```

Visually inspecting all 3 images using FSLeyes, I see no overlap and no gaps, which is a good sign:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/5ac5909a-2ccf-4a77-aaf8-8988c52a94a1)

Now, running the `sct_process_segmentation` steps, then merging the `MEAN(area)` columns of all three output CSV files, I get:

<details>

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/f3652532-6222-45f4-95d5-2cd6b50bcacd)

</details>

So, you are absolutely correct -- the sum of the individual GM/WM areas does not match the area of the SC mask.

I also notice, though, that the computed angle values (which are used to perform angle correction) are very different across GM/WM/SC seg. So, I was curious if the differences would change if we instead computed CSA using `-angle-corr 0`, and we get:

<details>

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/2cd86208-7ced-4f94-922f-46a9f7aad6ee)

</details>

Aha! No differences. So, this is entirely due to the angle correction code, seen [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/fed99bc1ae345ffc6fc2cbc2cf143bac6b25f371/spinalcordtoolbox/process_seg.py#L70-L105).

----

My guess as to what's happening is that the "centerline" computed for angle correction purposes is different for all three segmentations, given the differing shapes of the GM/WM/SC segmentations. 

In theory, we would want use a consistent centerline for GM/WM (e.g. extract it from the full cord segmentation), then compute angle correction identically for both GM/WM. But, `sct_process_segmentation` does not have an option to pass in a pre-computed centerline. So, we would need to add a new command line argument for this. :thinking: 

----

I was concerned that this issue would affect all CSA values computed for GM/WM pairs. So, I checked the relevant SCT tutorial: [Using binary masks to compute CSA for gray and white matter](https://spinalcordtoolbox.com/user_section/tutorials/gray-matter-segmentation/gm-wm-metric-computation/csa-gm-wm.html). But, thankfully, it already recommends setting `-angle-corr 0`:

> `-angle-corr 0`: Normally, angle correction will be applied during sct_process_segmentation to account for scans where the spinal cord is positioned at an angle with respect to the superior-inferior axis. While this works well when the input is a full spinal cord segmentation, in this case we are instead providing GM/WM segmentations only. The shape of these segmentations can have a negative effect on so the estimation of the cord centerline, which in turn may cause the estimated angle to be incorrect. So, here we specify 0 to turn off angle correction.

It looks like we were already aware of this issue!

**Comment by joshuacwnewton** [comment] 2024-02-13 20:53
@jcohenadad -- Would it be a desirable feature to allow users to input a centerline for angle correction, thus allowing for consistent CSA angle correction on GM/WM segmentation pairs?

**Comment by jcohenadad** [comment] 2024-02-14 02:03
> @jcohenadad -- Would it be a desirable feature to allow users to input a centerline for angle correction (e.g. summed GM+WM), thus allowing for consistent CSA angle correction on GM/WM segmentation pairs?

yes, that's actually a pretty good idea

**Comment by BFCombes** [comment] 2024-02-15 07:34
Dear [joshuacwnewton](https://github.com/joshuacwnewton),

Thank you very much for your help. I indeed tried without angle correction, and I can find SC = GM+WM. Nevertheless, the mean area values are quite different if we compare with and without angle correction.
As it is the first time that I am using SCT and because I am not a programming expert by training, I do not really get everything from all the functions available. Therefore, if I understand well, you would rather recommend to input a centerline for angle correction rather than no angle correction at all?

Thank you for your time,
Benjamin

**Comment by jcohenadad** [comment] 2024-02-15 19:18
> you would rather recommend to input a centerline for angle correction rather than no angle correction at all?

It depends what you want to do with the analysis, what are your working hypotheses. Eg: if you are _only_ interested in quantifying the ration between WM and GM area, then the angle correction will be meaningless (because the same cos(theta) correction will apply to both quantities, which you will then divide). However, if you are interested in quantifying that _absolute_ CSA of the WM, and of the GM, separately, and using it do do some correlations (or any other analyses), then you should probably correct for that angle.

**Comment by BFCombes** [comment] 2024-02-16 13:32
> > you would rather recommend to input a centerline for angle correction rather than no angle correction at all?
> 
> It depends what you want to do with the analysis, what are your working hypotheses. Eg: if you are _only_ interested in quantifying the ration between WM and GM area, then the angle correction will be meaningless (because the same cos(theta) correction will apply to both quantities, which you will then divide). However, if you are interested in quantifying that _absolute_ CSA of the WM, and of the GM, separately, and using it do do some correlations (or any other analyses), then you should probably correct for that angle.

Our hypothesis is that one group of mice undergo neurodegeneration in the spinal cord. That would be mainly in the grey matter, but it would affect the white matter, probably in in the caudal regions. Therefore, as we do not have real hypothesis, we want to compare both the absolute values as well as ratio.
Here in this case, the goal would be to identify a segment, let's say thoracic part, and calculate the volume of GM and WM within this range of slices. Basically, our thoughts are that by multiplying the area of one slice by its thickness (need to figure out if we should use the theoretical thickness or the one calculated after angle correction in the column "LENGTH") we could calculate the volume for this slice. Then, we make the sum of all the slices identified within the range of slices to get the volume of the segment.
Let me know if I am not clear, but that would be the goal.

**Comment by jcohenadad** [comment] 2024-02-16 13:40
> Basically, our thoughts are that by multiplying the area of one slice by its thickness (need to figure out if we should use the theoretical thickness or the one calculated after angle correction in the column "LENGTH") we could calculate the volume for this slice.

wether you compute the volume or the area, based on your working hypotheses and experimental setup, angle correction _should_ be applied. 

BTW: i think that computing the volume could be misleading, because that volume needs to be defined between clear anatomical markers (eg: spinal rootlets C2 --> C6). If you don't have these clear markers across all mice, then the volume will vary tremendously across mice and will decrease your ability to see group diff (ie: increased variance). What I recommend instead is to compute the CSA (not the volume) between clear markers. Even if these markers vary slightly across mice, the CSA average is more forgiving than the volume (which is essentially the sum across CSA slicewise).

**Comment by BFCombes** [comment] 2024-02-16 13:49
> > Basically, our thoughts are that by multiplying the area of one slice by its thickness (need to figure out if we should use the theoretical thickness or the one calculated after angle correction in the column "LENGTH") we could calculate the volume for this slice.
> 
> wether you compute the volume or the area, based on your working hypotheses and experimental setup, angle correction _should_ be applied.
> 
> BTW: i think that computing the volume could be misleading, because that volume needs to be defined between clear anatomical markers (eg: spinal rootlets C2 --> C6). If you don't have these clear markers across all mice, then the volume will vary tremendously across mice and will decrease your ability to see group diff (ie: increased variance). What I recommend instead is to compute the CSA (not the volume) between clear markers. Even if these markers vary slightly across mice, the CSA average is more forgiving than the volume (which is essentially the sum across CSA slicewise).

That makes sense. The problem is that as the mouse spinal cord is quite small, the markers are not that clear. Therefore, in order to dilute the mistakes in identifying these markers, we were thinking in taking this range of slices. Basically, we know that thoracic segment in a mouse is around 16mm, so here the idea was to identify the 320 slices (320 * 50um = 16mm) of our thoracic segment. Thanks to this, even if these markers vary slightly across mice as you said, we believe we will have reproducible measurements. And in this case, we might compute the CSA rather than the volume.

**Comment by jcohenadad** [comment] 2024-02-16 14:17
right, if you select the same number of slices across mice, then the volume will simply be the average CSA multiplied by a scalar (so there is no _gained_ information in terms of anatomical delineation along the S-I axis, and the concept of volume becomes misleading). So average CSA is definitely the way to go.

> Do you think it is a good point to take a defined range of slices, or we should better focus on clear markers and make the slices range vary a bit?

i have not looked at your data so I cannot comment on it. If you are confident you cannot clearly identify fiducial markers, then i guess you have no other choice.

**Comment by jcohenadad** [comment] 2024-02-16 14:48
> If that's the case, then I can prioritize implementing this in sct_process_segmentation (while ensuring that CSA for GM + WM = SC when angle correction is applied).

i think that angle correction can already be applied. Example:
1. run sct_process_segmentation using SC seg with slicewise=1 and angle corr
2. run sct_process_segmentation using GM seg with slicewise=1 and no angle corr
3. get the angle from the output CSV from step 1
4. apply angle corr to the output CSV from step 2 (multiplication by cos(theta), i think -- but we can check)

then, about the verification that CSA WM+GM=SC, i would do it the other way around, ie: segment SC and GM, and get WM by doing SC-GM. And run steps 2-4 above on WM seg

**Comment by joshuacwnewton** [comment] 2024-02-19 22:07
> apply angle corr to the output CSV from step 2 (multiplication by cos(theta), i think -- but we can check)

The more I think about it, the less certain I am about multiplying the total CSA of the GM/WM using the `cos` factors.

My (very naive) observations are:

- Multiplying the total area by `cos(angle_RL)*cos(angle_AP)` neglects the interpolation done during `-angle-corr 1`, resulting in slightly different area values depending on the shape of the cross section (as demonstrated in [this comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4378#issuecomment-1953182226))
- But, even for `-angle-corr 1`, the fact that we start with uncorrected axial slices means that we [don't capture the true cross-sectional shape of the GM/WM](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4378#issuecomment-1953195918), i.e. we don't use the plane orthogonal to the centerline at each point in the cord.

Would either of these observations have an effect on @BFCombes' research?

**Comment by joshuacwnewton** [comment] 2024-02-22 19:07
We discussed this issue in the 2024-02-21 SCT meeting, and we concluded that both of the concerns I [raised above](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4367#issuecomment-1953212351) are not actually issues for SCT:

- The method of "multiplying axial CSA directly by the computed angles" is sufficient for the research that @BFCombes is performing.
- Computing the CSA of perpendicular slices (rather than axial slices) would be a lot of work for very little meaningful gain -- our current angle correction method is largely sufficient.

That said, we may want to update our code and/or documentation to aid future users, either by:

1. Updating the tutorial to explain how to perform the "simple multiplication" method.
   - The one downside to this method is that it is a bit tedious to do. Both @BFCombes and I had our own individual spreadsheets, and it required a lot of manual work and double-checking to make sure we had the right values. 
2. Implementing the "input centerline" flag to standardize angle correction for GM/WM. (I have actually already done this, because I wanted to verify my own spreadsheet work :sweat_smile:)
   - If we did this, then it would automate the calculations, which could be especially important for batch processing (since that would involve a lot of manual spreadsheet work!)

Whichever approach we decide on, we probably want to also update the [current tutorial](https://spinalcordtoolbox.com/user_section/tutorials/gray-matter-segmentation/gm-wm-metric-computation/csa-gm-wm.html), which simply recommends `-angle-corr 0` -- definitely not sufficient in cases like this.

**Closed** 2024-03-22 04:43 UTC
Labels: sct_process_segmentation, feature
