### ISSUE TITLE
When using -rescale with -init-mask or -init-centerline, the later are not rescaled

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2538] opened 2019-11-29 17:52 UTC
When dealing e.g. with pediatric images, the option -rescale enables to change the affine matrix of the input image to "trick" the algo in that the cord appears bigger than it actually is (to match the adult size).

However, if the user combines the rescaling flag with the input mask or centerline, the latter input is not rescale, while it should be.

**Comment by joshuacwnewton** [comment] 2023-01-19 15:24
In the current codebase, it looks like `rescale_header` is applied to both `-init-mask` and `-init-centerline`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/377bfb88a9845bb8348e760aea5d70bb4f4bcb42/spinalcordtoolbox/scripts/sct_propseg.py#L514-L517

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/377bfb88a9845bb8348e760aea5d70bb4f4bcb42/spinalcordtoolbox/scripts/sct_propseg.py#L524-L527

These codeblocks were added in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/1926, which specifically mentions:

> If `-init-centerline` or `-init-mask` is used along with `-rescale`, the input labels are rescaled.

Closing as resolved.

**Comment by joshuacwnewton** [comment] 2023-01-19 15:25
Oh wait, sorry. This issue was opened after #1926, so it's possible that this is a bug, not a feature request.

Let me quickly double-check that this functionality actually works.

**Comment by joshuacwnewton** [comment] 2023-01-19 15:38
I ran the command:

```
sct_propseg -c t2 -i t2/t2.nii.gz -init-centerline t2/t2_centerline-optic.nii.gz -rescale 0.5
```

Then set a breakpoint to make sure that the command runs (it does):

![image](https://user-images.githubusercontent.com/16181459/213485429-b818152f-f751-4746-b409-2b9f24257618.png)

I then compared the two centerline files to make sure that the rescaling actually works.

The qform is rescaled:

![image](https://user-images.githubusercontent.com/16181459/213485348-25384d0b-5286-4985-9448-3abe2357b620.png)

![image](https://user-images.githubusercontent.com/16181459/213485148-2a7a9055-9c64-4e41-ba67-b6247b6dc926.png)

The sforms, on the other hand, remain unchanged. This seems to be by design, though:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/377bfb88a9845bb8348e760aea5d70bb4f4bcb42/spinalcordtoolbox/scripts/sct_propseg.py#L415-L421

So, it looks like everything had been working as expected, even prior to the creation of this issue.

**Closed by joshuacwnewton** 2023-01-19 15:38 UTC
Labels: sct_propseg, feature
