### ISSUE TITLE
ERROR: VirtualSampledPointSet must have 1 or more points. When using Gaussian masks in SliceReg

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3075] opened 2020-12-03 15:09 UTC
### Context

When using `sct_register_multimodal` with `algo=slicereg` and a Gaussian (ie non-binary) mask, the function crashes.

<details><summary>Output error</summary>

```
--
ESTIMATE TRANSFORMATION FOR STEP #1

Apply transformation from previous step

Parse list of warping fields...

Get dimensions of data...
  192 x 260 x 320 x 1

Apply transformation...

Apply transformation and resample to destination space...
Copy affine matrix from destination space to make sure qform/sform are the same.
Done! To view results, type:
fsleyes dest_RPI.nii src_reg.nii &
Registration parameters:
  type ........... im
  algo ........... slicereg
  slicewise ...... 0
  metric ......... CC
  iter ........... 10
  smooth ......... 0
  laplacian ...... 0
  shrink ......... 1
  gradStep ....... 0.5
  deformation .... 1x1x0
  init ...........
  poly ........... 5
  filter_size .... 5
  dof ............ Tx_Ty_Tz_Rx_Ry_Rz
  smoothWarpXY ... 2
  rot_method ..... pca

Traceback (most recent call last):
  File "/home/charley/sct-dev/scripts/sct_register_multimodal.py", line 413, in <module>
    main()
  File "/home/charley/sct-dev/scripts/sct_register_multimodal.py", line 389, in main
    path_out=path_out)
  File "/home/charley/sct-dev/scripts/sct_register_to_template.py", line 1038, in register_wrapper
    warp_forward_out, warp_inverse_out = register(src=src, dest=dest, step=step, param=param)
  File "/home/charley/sct-dev/scripts/sct_register_to_template.py", line 1204, in register
    verbose=param.verbose,
  File "/home/charley/sct-dev/spinalcordtoolbox/registration/register.py", line 189, in register_step_ants_slice_regularized_registration
    status, output = run_proc(cmd, verbose, is_sct_binary=True)
  File "/home/charley/sct-dev/spinalcordtoolbox/utils/sys.py", line 295, in run_proc
    raise RuntimeError(output)
RuntimeError: setting mask mask_crop.nii.gz
WARNING: In /__w/ANTs/ANTs/antsbin/staging/include/ITK-5.1/itkObjectToObjectMetric.hxx, line 579
Self (0x506f770): No valid points were found during metric evaluation. For image metrics, verify that the images overlap appropriately. For in$

WARNING: In /__w/ANTs/ANTs/antsbin/staging/include/ITK-5.1/itkObjectToObjectMetric.hxx, line 579
Self (0x49b2c60): No valid points were found during metric evaluation. For image metrics, verify that the images overlap appropriately. For in$

WARNING: In /__w/ANTs/ANTs/antsbin/staging/include/ITK-5.1/itkObjectToObjectMetric.hxx, line 579
Self (0x49b2c60): No valid points were found during metric evaluation. For image metrics, verify that the images overlap appropriately. For in$

Exception caught:
itk::ExceptionObject (0x49b20d0)
Location: "unknown"
File: /__w/ANTs/ANTs/antsbin/staging/include/ITK-5.1/itkImageToImageMetricv4.hxx
Line: 270
Description: itk::ERROR: Self(0x4d053e0): VirtualSampledPointSet must have 1 or more points.
```

</details>

This is a known issue. ANTs' SliceReg only accepts binary masks: https://github.com/neuropoly/spinalcordtoolbox/issues/2630

In the past i've implemented a hack to be able to use soft masks https://github.com/neuropoly/spinalcordtoolbox/pull/2634. The hack consists in multiplying the target image with the Gaussian mask:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/6129ec7ccb16b777462d57276e1f63498a1f9ef2/spinalcordtoolbox/moco.py#L527

However this hack was only implemented for the moco API. The issue needs to be addressed for `sct_register_multimodal`. 

Also see:  https://github.com/ivadomed/pipeline-hemis/issues/3

### Potential solution

- Multiply the target image by the Gaussian mask (this should probably be done in the API, before running slicereg).
- Add a check at the beginning of the function, and throw an informed error about it.

I would go with option 1.

**Comment by leandervaneekelen** [comment] 2020-12-04 11:21
I can implement this, given that I also need this fixed for https://github.com/ivadomed/pipeline-hemis/issues/3 and I'm the owner of that issue.

**Comment by joshuacwnewton** [comment] 2021-06-25 13:53
While trying to fix-up PR #3083, I wrote a test to represent https://github.com/ivadomed/pipeline-hemis/issues/3:

(I tried replicating the same commands from the HeMIS scripts: [`sct_create_mask`](https://github.com/ivadomed/pipeline-hemis/blob/a3dfa2d449cb555676d60cc0fd5e9b5399ae8149/registration_scripts/register_pipeline.sh#L128-L133) and [`sct_register_mulitmodal`](https://github.com/ivadomed/pipeline-hemis/blob/a3dfa2d449cb555676d60cc0fd5e9b5399ae8149/registration_scripts/register_pipeline.sh#L145-L152]).)

```python
def test_sct_register_multimodal_slicereg_with_gaussian_softmask(tmp_path):
    fname_mask = str(tmp_path/'mask_t2.nii.gz')
    sct_create_mask.main(['-i', sct_test_path('t2', 't2.nii.gz'),
                          '-p', f"centerline,{sct_test_path('t2', 't2_centerline-manual.nii.gz')}",
                          '-o', fname_mask, '-f', 'gaussian'])
    sct_register_multimodal.main([
        '-i', sct_test_path('t1', 't1w.nii.gz'),
        '-d', sct_test_path('t2', 't2.nii.gz'),
        '-dseg', sct_test_path('t2', 't2_seg-manual.nii.gz'),
        '-m', fname_mask,
        '-param', "step=1,type=im,algo=slicereg,metric=CC",
        '-ofolder', str(tmp_path),
    ])

    for path in ["mask_t2.nii.gz", "t2_reg.nii.gz", "t1w_reg.nii.gz", "warp_t22t1w.nii.gz", "warp_t1w2t2.nii.gz"]:
        assert os.path.exists(tmp_path/path)
```

The strange thing is, I'm not able to reproduce the error; the `isct_antsSliceRegularizedRegistration` command seems to work just fine with a soft mask:

```console
`sct_register_multimodal` -> `register.py` -> `register_step_ants_slice_regularized_registration()`

> isct_antsSliceRegularizedRegistration -t "Translation[0.5]" \
>                                       -m "CC[dest_RPI_crop.nii,src_reg_crop.nii,1,4,None,0.2]" \
>                                       -p 5 -i 10 -f 1 -s 0 -v 1 \
>                                       -o "[step1,src_reg_crop_regStep1.nii]" \
>                                       -x mask.nii.gz
 setting mask mask.nii.gz
Loop0 polyerr: 0 image-metric -55
Loop1 polyerr: 0 image-metric -55
```

Checking the final registration results in FSLeyes:

<details>
<summary> Large screenshots </summary>

----

**Gaussian softmask**:

![Screenshot from 2021-06-25 09-34-45](https://user-images.githubusercontent.com/16181459/123432734-aaaad600-d598-11eb-80bf-5fc361840d8e.png)

----

**t1w.nii.gz** and **t2_reg.nii.gz**:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/16181459/123433290-49cfcd80-d599-11eb-909d-ac833ff8c87d.gif)

----

</details>

----

Is it possible this was fixed upstream at some point? 

@kousu updated the binaries in #2821 (Aug 2020), SCT v5.0.0 was released in Nov 2020, and this error was reported Dec 2020. 
Could it be possible that no one had done a reinstall before testing (so everyone still had the old binaries in their dev SCT folders)?

**Comment by joshuacwnewton** [comment] 2021-06-26 18:52
My first thought is that maybe this was fixed in a newer version of the ANTSs binary. See https://github.com/ANTsX/ANTs/issues/823:

> Thanks, I think [an update] might fix it. There were some problems with the new ITK representations of masks for a while earlier this year [2019].

So, I ran the test from https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3075#issuecomment-868515856 across all of our platforms for various binary releases of ours:

* [Dec 2018 binaries](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/974504621)
* [Sept 2019 binaries](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/974529405)
* [April 2020 binaries](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/974530479)
* [Aug 2020 binaries](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/974497543) (most current)

The relevant test (`test_sct_register_multimodal_slicereg_with_gaussian_softmask`) passes with every binary on all platforms.

----

Thinking `sct_testing_data` might not be enough to reproduce, I tried using `sct_example_data`, as well as subjects from `spinegeneric/data-multi-subject`:

<details>
<summary> Modified test for `data-multi-subject` with a sampling of different subjects </summary>

```python
@pytest.mark.parametrize('subject', ['sub-cardiff03', 'sub-hamburg01', 'sub-juntendo750w01', 'sub-mpicbs06',
                                    'sub-oxfordFmrib07', 'sub-oxfordFmrib11', 'sub-sapienza05', 'sub-strasbourg04',
                                    'sub-tokyoSkyra06', 'sub-unf01'])
def test_sct_register_multimodal_slicereg_with_gaussian_softmask(tmp_path, subject):
    """
    Reproduction of ANTs error when using softmask with `isct_antsSliceRegularizedRegistration -x`.
    See also: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3075
    """
    prefix = f'data_example_spinegeneric/{subject}/anat/{subject}_'

    sct_deepseg_sc.main(['-i', f'{prefix}T2w.nii.gz', '-c', 't2',
                         '-o', f'{prefix}T2w_seg.nii.gz'])

    sct_get_centerline.main(['-i', f'{prefix}T2w.nii.gz', '-c', 't2',
                             '-o', f'{prefix}T2w_centerline'])

    fname_mask = str(tmp_path / 'mask_t2.nii.gz')
    sct_create_mask.main(['-i', f'{prefix}T2w.nii.gz',
                          '-p', f"centerline,{prefix}T2w_centerline.nii.gz",
                          '-o', fname_mask, '-f', 'gaussian'])

    sct_register_multimodal.main([
        '-i', f'{prefix}T1w.nii.gz',
        '-d', f'{prefix}T2w.nii.gz',
        '-dseg', f'{prefix}T2w_seg.nii.gz',
        '-m', fname_mask,
        '-param', "step=1,type=im,algo=slicereg,metric=CC",
        '-ofolder', str(tmp_path),
    ])
```

</details>

However, again this test passes for me locally (Ubuntu 20.04) across all subjects. I'm especially confused by this, because the HeMIS scripts [use `data-multi-subject`](https://github.com/ivadomed/pipeline-hemis/blob/a3dfa2d449cb555676d60cc0fd5e9b5399ae8149/start_registration.sh#L6), too.

----

I have a feeling I'm doing something wrong here when trying to reproduce https://github.com/ivadomed/pipeline-hemis/issues/3#issuecomment-738048409. To me, ANTs' SliceReg seems to handle softmasks without any errors... :confused::question:

**Comment by joshuacwnewton** [comment] 2021-06-26 19:25
Thinking `sct_testing_data` might not be enough to reproduce, I tried using `sct_example_data`, as well as subjects from `spinegeneric/data-multi-subject`, _as well as_ resampling to 1mm [as was done in the HeMIS scripts](https://github.com/ivadomed/pipeline-hemis/blob/a3dfa2d449cb555676d60cc0fd5e9b5399ae8149/registration_scripts/register_pipeline.sh#L101):

<details>
<summary> Modified test for `data-multi-subject` with a sampling of different subjects </summary>

```python
@pytest.mark.parametrize('subject', ['sub-cardiff03', 'sub-hamburg01', 'sub-juntendo750w01', 'sub-mpicbs06',
                                    'sub-oxfordFmrib07', 'sub-oxfordFmrib11', 'sub-sapienza05', 'sub-strasbourg04',
                                    'sub-tokyoSkyra06', 'sub-unf01'])
def test_sct_register_multimodal_slicereg_with_gaussian_softmask(tmp_path, subject):
    """
    Reproduction of ANTs error when using softmask with `isct_antsSliceRegularizedRegistration -x`.
    See also: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3075
    """
    prefix = f'data_example_spinegeneric/{subject}/anat/{subject}_'

    sct_resample.main(['-i', f'{prefix}T2w.nii.gz', '-mm', '1x1x1', '-o', f'{prefix}T2w_r.nii.gz'])
    sct_resample.main(['-i', f'{prefix}T1w.nii.gz', '-mm', '1x1x1', '-o', f'{prefix}T1w_r.nii.gz'])

    sct_deepseg_sc.main(['-i', f'{prefix}T2w_r.nii.gz', '-c', 't2',
                         '-o', f'{prefix}T2w_seg.nii.gz'])

    sct_get_centerline.main(['-i', f'{prefix}T2w_r.nii.gz', '-c', 't2',
                             '-o', f'{prefix}T2w_centerline'])

    fname_mask = str(tmp_path / 'mask_t2.nii.gz')
    sct_create_mask.main(['-i', f'{prefix}T2w_r.nii.gz',
                          '-p', f"centerline,{prefix}T2w_centerline.nii.gz",
                          '-o', fname_mask, '-f', 'gaussian'])

    sct_register_multimodal.main([
        '-i', f'{prefix}T1w_r.nii.gz',
        '-d', f'{prefix}T2w_r.nii.gz',
        '-dseg', f'{prefix}T2w_seg.nii.gz',
        '-m', fname_mask,
        '-param', "step=1,type=im,algo=slicereg,metric=CC",
        '-ofolder', str(tmp_path),
    ])
```

</details>

However, again this test passes for me locally (Ubuntu 20.04) across all subjects. I'm especially confused by this, because if I'm not mistaken, the HeMIS scripts [use `data-multi-subject`](https://github.com/ivadomed/pipeline-hemis/blob/a3dfa2d449cb555676d60cc0fd5e9b5399ae8149/start_registration.sh#L6), too.

**Comment by jcohenadad** [comment] 2021-06-27 01:19
So, interestingly, I am also not able to reproduce this error. However, registration using a Gaussian mask did not produce any change to the input _source_ image (which is supposed to be registered to the _destination_ image). See for yourself in this QC report: [qc.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/6720877/qc.zip)

The first entry (bad registration-- no change to _source_ image) is done using a Gaussian mask generated using the following command:
~~~
sct_create_mask -i mt1_seg.nii.gz -p centerline,mt1_seg.nii.gz -size 30mm -f gaussian -o mask_mt1.nii.gz
~~~

The second entry is done without any input mask (good registration), and the third entry is done using a binary cylinder mask generated using the following command:
~~~
sct_create_mask -i mt1_seg.nii.gz -p centerline,mt1_seg.nii.gz -size 30mm -f cylinder -o mask_mt1_cylinder.nii.gz
~~~

So, while there is no more an error, it looks like the behaviour is not the expected one (which is even worst 😬 ).

**Comment by jcohenadad** [comment] 2021-06-27 01:23
Digging further by looking at the temporary outputs by setting `-r 0` and `-v 2` for full verbose, I notice that the slicewise CSV file contains only zeroes (which reflects the "no effect of the registration"):

**step1TxTy_poly.csv**

Tx | Ty
-- | --
0 | 0
0 | 0
0 | 0
0 | 0
0 | 0

**Comment by joshuacwnewton** [comment] 2021-06-27 02:43
Thank you for being diligent about this! I think I had been too tunnel-visioned on the error itself (rather than inspecting the registration results).

I think your suggestion is perfectly reasonable. I'm happy to continue on with the effort from #3083. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment] 2021-06-27 15:51
@jcohenadad While digging into the moco-specific code, I notice that you applied the softmask fix [very early on](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/634670e4e0e282d27abaf457def5feb49da9a1f6/spinalcordtoolbox/moco.py#L526-L535
), which means that the fix was applied to both [`isct_antsSliceRegularizedRegistration`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/634670e4e0e282d27abaf457def5feb49da9a1f6/spinalcordtoolbox/moco.py#L746-L759) _and_ [`isct_antsRegistration`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/634670e4e0e282d27abaf457def5feb49da9a1f6/spinalcordtoolbox/moco.py#L726-L745).

If both binaries need this fix, then [the previously proposed changes](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3083/files) wouldn't have been enough. (I'll try to double-check check this... ideally we should be testing both 2D and 3D registration.)

**Comment by joshuacwnewton** [comment] 2021-06-27 16:00
<details>
<summary> An aside... </summary>

We're currently going to end up with a lot of duplication, because both `moco.py` and `register.py` have their own individual calls to the ANTs binaries. Ideally, we would have a single wrapper for the binaries, then both `moco.py` and `register.py` would point to the wrapper. (That way, the exact same softmask steps get applied to _everything_ that calls the ANTs binaries.)

This would require a significant refactoring, though... I'd be happy to do this, but it would increase the scope of the changes quite a bit, and would be more difficult to review given the size of our current team.
</details>

**Comment by jcohenadad** [comment] 2021-06-30 02:10
> I notice that you applied the softmask fix very early on (also a second time here?).

i would need to dig longer into the code to be 100% sure, but i _think_ the first masking is done on the target image, while the second one is on the source image (ie: the one being registered to the target)-- to take with a grain of salt, what i'm saying might be wrong....

**Comment by jcohenadad** [comment] 2021-06-30 02:12
> I think this means that the fix was active for both isct_antsSliceRegularizedRegistration and isct_antsRegistration. If both binaries need this fix, then the previously proposed changes wouldn't have been enough.

yes, i agree with you. Thank you for catching that. we definitely need to spend some time digging into the codebase

**Comment by jcohenadad** [comment] 2021-06-30 02:12
> We're currently going to end up with a lot of duplication, because both moco.py and register.py have their own individual calls to the ANTs binaries. Ideally, we would have a single wrapper for the binaries, then both moco.py and register.py would point to the wrapper. (That way, the exact same softmask steps get applied to everything that calls the ANTs binaries.)

This would require a significant refactoring, though. There's even a TODO for this:

yes, it is my long time dream (~5 years) to unify this codebase

**Comment by joshuacwnewton** [comment] 2021-06-30 12:38
> yes, it is my long time dream (~5 years) to unify this codebase

I spent much of Monday taking a look at refactoring the registration code ([`jn/3075-refactor-registration-wrappers`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/commits/jn/3075-refactor-registration-wrappers) ) to try to provide a more unified interface to the ANTs binaries (e.g. https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/f85d9440f7c45f7ba899f62bbbec2b10f99883db). Unfortunately, my attempts at refactoring changed the resulting moco params significantly. 

My takeaway it would not be safe to touch this until we have a more thorough test suite for moco, and thus can better understand the effect of the changes.

<details>
<summary> More info about the current moco tests... </summary>

> Right now our main moco test checks if the output params are approximately equal to cached ground truth:
> 
> https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9fc0aefea0075fbf02c9193055d60f2b4e15b03a/unit_testing/cli/test_cli_sct_dmri_moco.py#L19-L23
> 
> If this check fails, though, it doesn't give us much qualitative feedback:
> 
> * The test fails in an identical way for changes of any magnitude (e.g. 1e-4 and 1e2), so it's hard to gauge the severity of a failing test.
> * The test displays the moco params as-is, and doesn't provide any message describing the issue, so it requires some thinking to figure out the real meaning of the change.
>
> I'd like to get #3373 merged soon, so that I can begin working on updating these tests incrementally.

</details>

<details>
<summary> Aside about rewriting... </summary>

> I think rewriting often sounds good on paper (I certainly convinced myself in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3075#issuecomment-869186099), but rewriting also [has a lot of pitfalls](https://www.anthropicstudios.com/2021/06/25/when-to-rewrite/):
> 
> > Eventually, after spending a lot of time on the rewrite, you either end up basically recreating what you already had, or you end up with something that solves your existing problem at the expense of a bunch of new ones. Sometimes, sometimes, you end up with a better system–but it’s usually one that you could’ve built more quickly through incremental changes to your old implementation.
> >
> > **A working system is a valuable asset. It works. It lets you test new ideas cheaply. Don’t take that for granted.**
> 
> That last sentence rings true for me, especially given how valuable reproducibility is for our algorithms. 
> 
> So, I think I need to be more biased against rewrites, and accept that in the short term, minor style/organizational issues are often [acceptable technical debt](https://airbrake.io/blog/software-development/acceptable-technical-debt).

</details>

**Comment by joshuacwnewton** [comment] 2021-06-30 12:39
> but i _think_ the first masking is done on the target image, while the second one is on the source image (ie: the one being registered to the target)

During my rewrite, I investigated this, and you are correct. This is notable to me, because currently in `sct_register_multimodal`, we advise that the mask will only be applied to the destination image:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/634670e4e0e282d27abaf457def5feb49da9a1f6/spinalcordtoolbox/scripts/sct_register_multimodal.py#L135-L140

And indeed, in #3083, Leander applied the softmask only to the destination image.

**Comment by jcohenadad** [comment] 2021-06-30 14:34
> This makes me wonder... is it OK that we would have a different approach for both functions? (i.e. We apply the mask to src/dest for moco, but only dest for registration.) Or, should we try and be consistent here?

fantastic question. I do not have the answer. One element of answer though, is that for moco we would expect volume _i_ (of a 4D data) to be close to the target, and therefore be also close to a mask computed from the target (typically, cord segmentation is ran on the 4D volume average across time _before, moco_ and a mask is created from it)-- therefore there is no risk in using the same mask to mask volume _i_ and the target, whereas in register_multimodal, we don't really know how far apart the source and target volumes are, therefore applying a mask (estimated from the target image) on the source image might actually crop relevant parts of the anatomy-- so i _think_ that's the reasoning behind it, but maybe i'm totally wrong and there was no reasoning at all for this choice

**Comment by joshuacwnewton** [comment] 2021-06-30 16:05
> whereas in register_multimodal, we don't really know how far apart the source and target volumes are, therefore applying a mask (estimated from the target image) on the source image might actually crop relevant parts of the anatomy

I would also be curious to verify how `antsSliceRegularizedRegistration` and `antsRegistration` work internally. If ANTs is applying binary masks to only the destination image, but we would applying the mask to both src and dest, then there might be a subtle difference between how binary and softmasks are treated.

**Closed** 2021-07-13 15:47 UTC
Labels: API: registration, bug, good first issue, sct_register_multimodal
