### ISSUE TITLE
Input image is overwritten if no output file is specified

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3131] opened 2020-12-26 20:12 UTC
### Description

Running this innocent command:
~~~
sct_image -i image.nii.gz -setorient RPI
~~~
Will overwrite the input image 😬 .

We definitely want to avoid this behaviour, and instead set the default output with a suffix corresponding to the type of processing applied. E.g., in this case, adding the suffix `_RPI`.

**Comment by RignonNoel** [comment] 2022-01-12 20:34
@jcohenadad I'm ok with you, this kind of automatic overwrite can really be annoying, I already had the problem myself in the last few days when I was rampup on SCT.

However it seems to me that the problem is generalized to all the system and not just to `sct_image`, the `Image.save()` method just print a warning message but do the overwrite without asking a different output or force option.

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/40781c1ac8bdd62f86d2103ea98a6a85f5d8aad4/spinalcordtoolbox/image.py#L503-L505

In my opinion, i think the best way to approach the problem would be to add a `force` argument to the `Image.save()` method and a generic `-f` argument to `SCTArgumentParser` so all the CLI will be able to block or allow some stateful change like the overwrite of the input files.

I think that since you already have some generic layer like `SCTArgumentParser` it's a doable task.

@joshuacwnewton If you have some opinion I will be happy to hear it and to work on this issue

**Comment by joshuacwnewton** [comment] 2022-01-14 15:56
> However it seems to me that the problem is generalized to all the system and not just to `sct_image`

Hmm. I think you make good points! There aren't really any safeguards in place right now to prevent unwanted overwriting.

Looking into it a little, though, I still think part of the problem is specific to `sct_image`? Just because right now, we are explicitly falling back to the name of the input image by default:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/304a934b3bb57b24885f6359a2cc35f6dc9c7033/spinalcordtoolbox/scripts/sct_image.py#L348-L350

So even if we made changes at the `Image.save()` level, I think we would still have a problem at the `sct_image` level, maybe? We would just end up with the file saving getting blocked, and so we would still have to make changes to `sct_image`, too.

**Comment by RignonNoel** [comment] 2022-01-21 22:38
@joshuacwnewton I see your point, but it's not because the `Image.save()` function is aware of the `force` argument that the script will no more be responsible of the user interface experience.

If we have a force args input we should be able to refactor the script from:
```
 if fname_out is None: 
     fname_out = fname_in[0]
```

to:
```
 if fname_out is None:
     if force is True: 
         fname_out = fname_in[0]
     else:
         raise a beautiful error message with some specific context
```

Preventing the Image.save() function to fail into it's own `force` security and improving the user interface.

---

The force argument of `Image.save()` is on the API layer, it's a more high-level question and could be done in an other issue with an other PR. Maybe we should just add a generic `force` arg to `SCTArgumentParser` and use it in the script for the moment.

After that it will be easy to progress on this security/experience question by sending the new info to the API layer.

**Comment by joshuacwnewton** [comment] 2023-01-15 00:27
Closing this issue as a duplicate. Issue https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/1615 is a superset of this issue.

**Closed by joshuacwnewton** 2023-01-15 00:27 UTC
Labels: enhancement, sct_image, good first issue
