### ISSUE TITLE
`sct_image -keep-vol` keeps 4D nii header when only a single 3D volume is specified

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4024] opened 2023-02-02 01:12 UTC
### Description

When splitting 4D image into three 3D images in the context of [this issue](https://github.com/ivadomed/canproco/issues/21) using `sct_image -keep-vol`:

```
sct_image -i sub-cal056_ses-M0_acq-MT_MTS.nii.gz -keep-vol 0 -o sub-cal056_ses-M0_acq-MTon_MTS.nii.gz
sct_image -i sub-cal056_ses-M0_acq-MT_MTS.nii.gz -keep-vol 1 -o sub-cal056_ses-M0_acq-MToff_MTS.nii.gz
sct_image -i sub-cal056_ses-M0_acq-MT_MTS.nii.gz -keep-vol 2 -o sub-cal056_ses-M0_acq-T1w_MTS.nii.gz
```

The headers of the created 3D images still contain "remains" from the original 4D image. 

Specifically, the first element of the `dim` entity is the same for 4D as well as 3D images:

```
# 4D
$ sct_image -i sub-cal056_ses-M0_acq-MT_MTS.nii.gz -header | grep dim | head -1 
dim		[4, 256, 256, 18, 3, 1, 1, 1]
```

```
# 3D
$ sct_image -i sub-cal056_ses-M0_acq-T1w_MTS.nii.gz -header | grep dim | head -1 
dim		[4, 256, 256, 18, 1, 1, 1, 1]
```

This can cause problems in consequent processing. For example, when running:

```
$ sct_register_multimodal -i sub-cal056_ses-M0_acq-T1w_MTS.nii.gz -d sub-cal056_ses-M0_T2w.nii.gz
``` 

The function fails:

```
ValueError: File sub-cal056_ses-M0_acq-T1w_MTS.nii.gz has 4 dimensions! Accepted dimensions are: [3].
```

The error is raised by the `image.py/check_dim` function, which assumes `dim[0]=3`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/e1d46c06504d1fd66dfdea12a0678531b12fb77b/spinalcordtoolbox/image.py#L1456-L1466

[sub-cal056_MT.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/10563852/sub-cal056_MT.zip)

**Comment by valosekj** [comment] 2023-02-02 16:04
The reason for the same header between the input 4D image and the output 3D image is that the [`remove_vol`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/842b0422f1b6f1743be42d366927e1af5c7a9f8f/spinalcordtoolbox/scripts/sct_image.py#L495) function just simply copy the header:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/842b0422f1b6f1743be42d366927e1af5c7a9f8f/spinalcordtoolbox/scripts/sct_image.py#L516

This is not ideal, as mentioned in the TODO of another function:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/842b0422f1b6f1743be42d366927e1af5c7a9f8f/spinalcordtoolbox/image.py#L1542-L1543

**Comment by joshuacwnewton** [comment] 2023-02-02 16:49
I notice that the `remove_vol` function seems to assume that both the input and output will be 4D:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/842b0422f1b6f1743be42d366927e1af5c7a9f8f/spinalcordtoolbox/scripts/sct_image.py#L497-L501

I guess the issue here is that `-keep` assumes that you are keeping >1 volumes, and thus the output will be 4D: 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/842b0422f1b6f1743be42d366927e1af5c7a9f8f/spinalcordtoolbox/scripts/sct_image.py#L513-L514

But if `-keep` is specified with a single volume, then the output will be 3D, not 4D, breaking the above assumption.

```python
>>> array = np.empty([50, 50, 50, 50])
>>> slice = array[:, :, :, 1]
>>> slice.shape
(50, 50, 50)
```

And so the dim field must be updated accordingly.

**Comment by valosekj** [comment] 2023-02-02 17:10
> I notice that the `remove_vol` function seems to assume that both the input and output will be 4D:

Ahh. Right! What is then the proper way to split a 4D image into several 3D volumes?

**Comment by joshuacwnewton** [comment] 2023-02-02 17:14
> What is then the proper way to split a 4D image into several 3D volumes

There is `sct_image -split t`?

**Comment by joshuacwnewton** [comment] 2023-02-02 17:14
That said, I still think this is a bug... It would make sense to me for `-keep-vol` to return a 3D volume if only 1 volume is selected.

This issue is also kind of similar in spirit to:

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/215

**Comment by valosekj** [comment] 2023-02-02 17:22
> > What is then the proper way to split a 4D image into several 3D volumes
> 
> There is `sct_image -split t`?

Ou, yes! `sct_image -split t` seems to work fine in this case:

```
$ sct_image -i sub-cal056_ses-M0_acq-MT_MTS.nii.gz -split t

$ sct_image -i sub-cal056_ses-M0_acq-MT_MTS.nii.gz -header | grep dim | head -1
dim		[4, 256, 256, 18, 3, 1, 1, 1]

$ sct_image -i sub-cal056_ses-M0_acq-MT_MTS_T0001.nii.gz -header | grep dim | head -1
dim		[3, 256, 256, 18, 1, 1, 1, 1]

```

**Comment by joshuacwnewton** [comment] 2024-01-30 19:35
Hrm. So, I went to fix this problem by not copying the `Image`, and instead creating a new `Image`, due to the recommendations from https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4024#issuecomment-1413983740:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/842b0422f1b6f1743be42d366927e1af5c7a9f8f/spinalcordtoolbox/image.py#L1542-L1543

However, I realized that copying the image is actually OK in this case, because the `dim` property _should_ get fixed when calling `header.set_data_shape` during `Image.save()`.

The real problem here is that the `remove_vol` function outputs a `[x, y, z, 1]` image instead of an `[x, y, z]` image. So, `set_data_shape` sets it to 4.

This is a tiny fix, so I'll open up a PR. :)

**Comment by joshuacwnewton** [comment] 2024-01-30 20:02
Hrm. I was going to solve this issue with a tiny PR, but the more I think about it, the more it feels like this falls under the umbrella of the [existing open issues](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4024#issuecomment-1414090071).

I feel like the question of "How should we handle single-volume 4D images?" is a much larger question, and I don't know if it makes sense to apply a fix here but nowhere else (especially since @valosekj already found an alternative in `-split t`.)

Closing as duplicate of #524.

**Closed** 2024-01-30 20:02 UTC
Labels: sct_image
