### ISSUE TITLE
Docker-hub is poorly maintained

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2965] opened 2020-10-22 20:00 UTC
Docker-hub hasn't been updated for 9 months. 

Some users try to install SCT via Docker, and end up with a non-up-to-date version of SCT (e.g. [here](https://forum.spinalcordmri.org/t/sct-toolbox-illegal-instruction-error/538))

Problem: 
- docker-hub needs to be updated everytime we do a release 
    - See: [`neuropoly/sct` DockerHub container](https://hub.docker.com/r/neuropoly/sct/) and [`sct_docker` repo](https://github.com/neuropoly/sct_docker)
- we don't do that, because we don't have the time.

Solution:
- Stop maintaining docker containers
- Offer a solution to install master version of SCT using "fresh" container as instructed [here](https://forum.spinalcordmri.org/t/sct-toolbox-illegal-instruction-error/538)

**Comment by joshuacwnewton** [comment] 2020-10-25 22:04
> we don't do that, because we don't have the time.

> Solution: Stop maintaining docker containers

I'm curious if there are steps we could take to make the release process easier. For example, if there were clear steps on [the "Creating a new release` dev Wiki page](https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release), would we follow through more reliably? 

I'm also wondering if this could this be handled via [Docker's automated builds](https://docs.docker.com/docker-hub/builds/), even.

**Comment by jcohenadad** [comment] 2020-10-26 14:53
> As an alternative, I'm curious if there are steps we could take to make the release process easier. For example, if there were clear steps on the "Creating a new release` dev Wiki page, would we follow through with updating Docker Hub more reliably?

if steps are clear and procedure takes 2min, then yes, it will likely happen. 

> I'm also wondering if this could this be handled via Docker Hub's automated builds, even. (For example, by providing a single "official" Dockerfile at the root of our repository.)

that would be awesome 🙌

So again, we come back to the situation: time to implement vs. potential gain. Personally, I find that:
- Docker users represent a minority of our users;
- these docker users are comfortable with a computer/terminal, and could easily install SCT from a fresh docker container, mitigating the need to support docker SCT versions.

**Comment by joshuacwnewton** [comment] 2020-10-27 00:32
> So again, we come back to the situation: time to implement vs. potential gain. Personally, I find that:
> 
> * Docker users represent a minority of our users;
> * these docker users are comfortable with a computer/terminal, and could easily install SCT from a fresh docker container, mitigating the need to support docker SCT versions.

I think this makes a lot of sense. Thank you for sharing these thoughts! In that case, Docker Hub releases (automated or not) would be a "nice to have" but not strictly necessary. 

If we find that Docker users become a larger part of our audience, then perhaps we can revisit, but for now I agree with your suggestion to move away from maintaining a Docker Hub release.

**Comment by jcohenadad** [comment] 2020-11-03 22:30
Documentation is no more pointing to dockerhub, so we can close

**Comment by joshuacwnewton** [comment] 2021-09-14 20:46
I'm reopening this issue because the [SCT docker-hub image](https://hub.docker.com/r/neuropoly/sct) is still available to be discovered by users, despite our documentation not pointing to it anymore. 

If we're taking the stance of not supporting or maintaining the image, we should consider removing our presence entirely from docker-hub and archiving [the associated repo](https://github.com/spinalcordtoolbox/sct_docker), lest our users be misled. (Case in point: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3518)

**Comment by joshuacwnewton** [comment] 2021-09-14 21:11
Re-closing as this is a duplicate of #3519. :stuck_out_tongue_closed_eyes:

**Closed by joshuacwnewton** 2021-09-14 21:11 UTC
