### ISSUE TITLE
-param gaussian_std is no more used and should be removed

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2235] opened 2019-04-18 15:42 UTC
This param flag is no more used with the new init_c2c3 SVM/HOG method and therefore should be removed from the usage (and the code where relevant)

**Comment by joshuacwnewton** [comment] 2023-01-17 23:27
This issue is a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3706. The parameter was removed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3841.

Closing as resolved.

**Closed by joshuacwnewton** 2023-01-17 23:27 UTC
