### ISSUE TITLE
Have the possibility to include a YML file to exclude subjects

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3629] opened 2021-12-17 16:56 UTC
For reproducibility, it would be nice to be able to input a YML file when running `sct_run_batch`. For example, after QCing results, realizing that some subjects have strong artifacts, we could list them in the repository of the data inside a 'exclude.yml' file, with, in comments, the reason for exclusion. 

Similarly to what was done here: https://github.com/spine-generic/data-multi-subject/blob/master/exclude.yml

**Comment by joshuacwnewton** [comment] 2021-12-17 17:13
Could this not already be accomplished via the `exclude`/`exclude_list` parameters that can be added as part of `sct_run_batch`'s  `config.yml`?

Or is the tricky part here that QC outputs its own YML file, which would then need to be copied and pasted to `sct_run_batch`'s config YML?

**Comment by jcohenadad** [comment] 2021-12-17 18:50
> Could this not already be accomplished via the exclude/exclude_list parameters that can be added as part of sct_run_batch's configuration file?

yes indeed, but currently these exclude/exclude_list parameters have to be manually written when typing the CLI syntax. Ideally, we would do something like this: `sct_run_batch -exclude exclude.yml`, so that a release results could be associated with a versioned-tracked exclude.yml file (and the results would not depend on what the user typed on the CLI syntax). Does that make sense?

**Comment by joshuacwnewton** [comment] 2023-01-30 01:10
Ah! I just realized that this is a duplicate of #3971. Closing.

**Closed by joshuacwnewton** 2023-01-30 01:10 UTC
Labels: feature
