### ISSUE TITLE
Various issues with Qt

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2865] opened 2020-08-30 20:20 UTC
A few users reported issues with Qt:
- https://forum.spinalcordmri.org/t/qt-qpa-plugin-issue/475
- https://forum.spinalcordmri.org/t/problem-with-sct-label-utils-v-4-3/465

Issues with Qt checking:
- https://forum.spinalcordmri.org/t/check-if-display-variable-is-set-fail-in-sct-check-dependencies/488/5
- https://github.com/neuropoly/spinalcordtoolbox/issues/2623

**Comment by cfhammill** [comment] 2020-08-31 21:14
I think the two issues may be independent. My working hypothesis for the first issue is that the user got unlucky and had a slightly broken install of `libxcb`. For the second I'm still lost, likely another version of Qt is floating around, but I don't have much to work off of until I get get some more environment details from the user.

**Comment by cfhammill** [comment] 2020-08-31 21:15
I notice that `sct_check_dependencies` isn't reporting an error for either user. In the first users case because the program worked successfully, and in the second because the error message is printed but `error` or `warning` is never displayed. We may need to consider increasing the sensitivity of the Qt test.

**Comment by kousu** [comment] 2020-12-15 21:19
(is this related to what I was trying to fix in https://github.com/neuropoly/spinalcordtoolbox/pull/2701 ? It's been a long time since I touched that PR so I am unsure.)

**Comment by joshuacwnewton** [comment] 2023-01-21 20:59
I'd like to close this as a `WONTFIX` for pragmatic reasons:

- The first two forum posts are very environment-specific, and require debugging/investigation on the machine in question. Given that this issue is more than 2 years old at this point, I'm doubtful we'll be able to make any progress with only the information we have now.
- I believe the third forum post would ikely have been resolved by recent refactorings to how we check `DISPLAY` via `sct_check_dependencies` ([#3420](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3420)).
- The last link (the SCT issue) was closed for the following reason:

   > Closing for now, we will reopen if the error is reproduced

I think I'd like to take the same approach here. (Close the issue for now, investigate if the issues reappear.)

**Closed by joshuacwnewton** 2023-01-21 20:59 UTC
Labels: priority:HIGH, user requested
