### ISSUE TITLE
Refactor sct_convert

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2648] opened 2020-03-30 18:35 UTC
### Context

`sct_convert` was created to convert between various image files (minc, mgz, nii, nii.gz, etc.). Now, it is only used within SCT to convert between nii and nii.gz. The docstring of this function is missing, and the functional part of the script should be made a callable module. 

### Suggestions

We should refactor this function. Either drop the CLI, or replace it with e.g. `sct_image -i TYPE1 o- TYPE2`, since `sct_image`'s job is to deal with images. 

We should also create a python module for the functional part, with proper docstrings.

**Comment by joshuacwnewton** [comment] 2023-01-14 19:13
Duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3955.

**Closed by joshuacwnewton** 2023-01-14 19:13 UTC
Labels: refactoring
