### ISSUE TITLE
add the possibility to track events on sentry for analytics

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1905] opened 2018-07-04 16:04 UTC
e.g. to be able to count the number of installations

**Comment by joshuacwnewton** [comment] 2023-01-17 18:23
Closing this issue as a duplicate of our other "Fix Sentry" issue: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3079.

**Closed by joshuacwnewton** 2023-01-17 18:23 UTC
