### ISSUE TITLE
Replace verbose flag in API with environment variable

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2853] opened 2020-08-18 18:51 UTC
Currently a lot of scripts and API functions in SCT need to carry a flag 'verbose', which sets the logging level at the beginning of the CLI. More details [in the wiki](https://github.com/neuropoly/spinalcordtoolbox/wiki/logging#how-logging-appears-to-users-of-sct-scripts).

Instead of keep maintaining a verbose argument across all functions, which is prone to errors (e.g. https://github.com/neuropoly/spinalcordtoolbox/pull/2852), why not getting rid of it and instead rely on the logging level?

**Comment by joshuacwnewton** [comment] 2020-08-18 20:44
I very much agree with the spirit of having a unified verbose setting.

Another possible point in favor of a change is, currently, passing around per-function `verbose` arguments leads to unintuitive behavior like this: 
```python
sct.run(['sct_label_utils', '-i', 'point_RPI.nii'], verbose=param.verbose)
```
When I read this for the first time, I assumed `verbose` here would control the verbosity for the script that was being run (i.e.`sct_label_utils`). But, it turns out to get `sct_label_utils` to run in verbose mode, you'd have to set a second verbose parameter like this:
```python
sct.run(['sct_label_utils', '-i', 'point_RPI.nii', '-v'], verbose=param.verbose)
```
I think this sort of behavior could be improved with the suggestion you're making, @jcohenadad.

**Comment by joshuacwnewton** [comment] 2020-08-19 16:42
This issue possibly overlaps with #1968.

**Comment by joshuacwnewton** [comment] 2023-01-14 16:53
Duplicate of #1968.

**Closed by joshuacwnewton** 2023-01-14 16:53 UTC
