### ISSUE TITLE
`isct_propseg` binary stalls when `-cross` and `-CSF` are both passed together (for specific input data)

### ISSUE THREAD

**Issue by sercharpak** [spinalcordtoolbox/spinalcordtoolbox#3608] opened 2021-12-01 15:32 UTC
### Description

I am using sct_propseg to segment the CSF (I support the idea of having a csf segmentation DL solution #2277 ). 

Currently sct_propseg outputs:

```
image_to_segment_centerline.nii.gz              InitialTube1.vtk
image_to_segment_centerline.txt                 InitialTube2.vtk
image_to_segment_cross_sectional_areas_CSF.txt  InitialTubeCSF1.vtk
image_to_segment_cross_sectional_areas.txt      InitialTubeCSF2.vtk
image_to_segment_CSF_mesh.vtk                   segmentation_CSF_mesh_low_resolution.vtk
image_to_segment_mesh.vtk                       segmentation_mesh_low_resolution.vtk
image_to_segment_seg.nii.gz
```
but it is missing the `image_to_segment_CSF_seg.nii.gz` that I want to use and edit.

It keeps executing (for several hours until I interrupted it) but it doesn't output anything else.

### Steps to Reproduce

```
--
Spinal Cord Toolbox (5.4)

sct_propseg -i image_to_segment.nii.gz -ofolder image_to_segment_propseg -c t2 -CSF
--

Creating temporary folder (/tmp/sct-20211130170257.313831-label_vertebrae-7r8vxqzz)
Creating temporary folder (/tmp/sct-20211130170257.314729-b79mq_zw)
Remove temporary files...
rm -rf /tmp/sct-20211130170257.314729-b79mq_zw
/path/to/sct/sct_5.4/bin/isct_propseg -t t2 -o ipath/to/folder/containing/image/image_to_segment_propseg -verbose -mesh -centerline-binary -CSF -centerline-coord -cross -init-tube -low-resolution-mesh -i /path/to/folder/containing/image/image_to_segment.nii.gz -init-centerline /tmp/sct-20211130170257.313831-label_vertebrae-7r8vxqzz/centerline_optic.nii.gz -centerline-binary # in /path/to/folder/containing/image/
```

**Comment by joshuacwnewton** [comment] 2021-12-01 16:05
Hi @sercharpak! Would you be able to share the `image_to_segment.nii.gz` file, so that we can try to reproduce the issue?

**Comment by jcohenadad** [comment] 2021-12-01 23:36
FWIW: I downloaded the images and I am able to reproduce the issue: _veeeeeery_ slow computation time, which is abnormal (I stopped after 15min).

**Comment by sercharpak** [comment] 2021-12-02 10:24
Little update from my side: 
I had an "old" installation of SCT (4.3) and it didn't get stuck.

**Comment by joshuacwnewton** [comment] 2021-12-02 17:26
This is very obscure bug! It occurs due to a combination of 3 factors:

1. The stall is data-dependent. (The command stalls with your data, but succeeds with our test data `sct_example_data/t2.nii.gz`.)

2. The stall occurs when `isct_propseg -cross` is combined with `isct_propseg -CSF`. (Both arguments succeed when run individually using your data.)
    
    <details> 
    
    I ran `sct_propseg -i image_to_segment.nii.gz -ofolder image_to_segment_propseg -c t2 -CSF` on both `master` and `v4.3`, this time using `-v 2` to capture the output of our compiled C++ binary `isct_propseg`. Then, I [compared the two output logs](https://www.diffchecker.com/xAyuju2V).
    
    Interestingly, the majority of the processing steps (propagation, error calculations, etc.) are identical! This is confirmed by comparing the checksums for `isct_propseg` binary: the two binaries are identical between versions.
    
    ```console
    joshua@tadpole:~/Desktop$ md5sum isct_propseg_4.3 isct_propseg_5.4
    091990aca2475d053e8b57bbcbc42437  isct_propseg_4.3
    091990aca2475d053e8b57bbcbc42437  isct_propseg_5.4
    ```
    
    However, what _does_ differ is that the more recent command has 5 additional arguments (`-mesh`, `-centerline-coord`, `-cross`, `-init-tube`, `-low-resolution-mesh`) by default:
    
    ```diff
    # 4.3 isct_propseg command
    isct_propseg -t t2 -o image_to_segment_propseg -verbose -CSF -i 1_image_to_segment.nii.gz -init-centerline centerline_optic.nii.gz -centerline-binary 
    
    # master isct_propseg command
    isct_propseg -t t2 -o image_to_segment_propseg -verbose -mesh -centerline-binary -CSF -centerline-coord -cross -init-tube -low-resolution-mesh -i 1_image_to_segment.nii.gz -init-centerline centerline_optic.nii.gz -centerline-binary 
    ```
    
    If I remove all 5 of these extra arguments, I can get it to run without stalling on `master`. :tada: 
    
    Next, I looped through all 5 arguments one at a time to see if a specific argument would cause the stall. Of the 5 arguments, `-mesh`, `-centerline-coord`, `-init-tube`, and `-low-resolution-mesh` worked fine. 
    
    Only `-cross` causes a stall.
    
    </details>

3. The  `-cross` argument was set despite the fact that `-cross` wasn't passed to `sct_propseg`! This is due to a separate bug that was introduced in [#2842](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2842):

    <details>
    
     Because of the changes in that PR, `-cross` was parsed with the following check:
    
    https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/422d91afd1236edfab7b7634112b16a2420a1d47/spinalcordtoolbox/scripts/sct_propseg.py#L480-L481
    
    However, `is not None` doesn't work here, since `-cross` is either `True` or `False`. 
    
    https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/422d91afd1236edfab7b7634112b16a2420a1d47/spinalcordtoolbox/scripts/sct_propseg.py#L263-L67
    
    So the check will always evaluate to `True`, _always_ enabling `-cross` regardless of whether it was asked for.
    
    In fact, _all_ of the boolean arguments are turned on by default. This shouldn't happen.
    
    </details>

The bug in 3. can be fixed immediately, and will allow `-CSF` to be run without error. 

However, 1./2. are a little trickier, since it involves investigating the data-specific behavior of the intersection between `-CSF` and `-cross` inside of our `isct_propseg` C++ binary. So for now, I think it would be best to focus on the short-term fix.

**Comment by joshuacwnewton** [comment] 2021-12-02 18:08
As an aside, this question also exposed another bug inside `check_and_correct_segmentation()` function.

The following line will fail when `-ofolder` is passed:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/422d91afd1236edfab7b7634112b16a2420a1d47/spinalcordtoolbox/scripts/sct_propseg.py#L136-L137

But the path here is incorrect. `fname_seg_absolute` was determined _after_ the temporary directory switch:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/422d91afd1236edfab7b7634112b16a2420a1d47/spinalcordtoolbox/scripts/sct_propseg.py#L57-L64

So, the path incorrectly points to a nonexistent file in the `tmp` directory. Ergo, we need to get the original path _before_ we switch directories.

**Comment by joshuacwnewton** [comment] 2022-07-26 12:42
Given:

* The very specific nature of the conditions that produce this bug
* The fact that there's an easy workaround (running `-cross` and `-CSF` separately)
* The difficulty of making changes to the `isct_propseg` binary (debugging C++ code, recompiling it across platforms, etc.) 
 
I'm going to tentatively mark this as a `WONTFIX`, and close the issue in an effort prune our user-requested issue backlog and aid with triaging.

**Closed by joshuacwnewton** 2022-07-26 12:42 UTC
Labels: bug, sct_propseg, user requested
