### ISSUE TITLE
sct_maths operation with a scalar corrupt header

### ISSUE THREAD

**Issue by SaraDupont** [spinalcordtoolbox/spinalcordtoolbox#744] opened 2016-02-26 16:39 UTC
`sct_maths` used with a scalar change the value of `sct_slope` and `scl_inter` in the header:

path do data: `/Volumes/folder_shared/sdupont/2016-01-26-GM_challenge_data/epm_error_fslview`
command used: `sct_maths -i p01_t2star_gmseg_SD.nii.gz -mul 2 -o p01_t2star_gmseg2_SD.nii.gz`

header before multiplication: 
![before_mul_2](https://cloud.githubusercontent.com/assets/5857909/13358307/a2d59278-dc7c-11e5-976e-d6e0440c3f3b.png)

header after multiplication:
![after_mul_2](https://cloud.githubusercontent.com/assets/5857909/13358314/ad66baaa-dc7c-11e5-82da-7a9556c1d52a.png)

This error in the header seems to affect the behaviour of fslview pencil tool: the value set for a voxel is not the chosen value.

I suggest to look into the function `get_data_or_scalar()`  from `sct_maths`as this issue occurs only during an operation with a scalar, not with an image data.

**Comment by joshuacwnewton** [comment] 2022-11-22 17:17
Oh my gosh... I'm fairly certain this issue is a duplicate of #3943/#3232, _5 whole years_ before we recognized and understood this behavior.

> _(I'm guessing what happened here is that the data array became `FLOAT64` after the multiplication, and the header stayed `INT16`, causing float-int scaling. This will be fixed by #3944.)_

I'm closing as a duplicate, but... wow! Good catch, @SaraDupont.

**Closed by joshuacwnewton** 2022-11-22 17:17 UTC
Labels: bug, sct_maths
