### ISSUE TITLE
matplotlib.backends.backend_qt4agg removed

### ISSUE THREAD

**Issue by kousu** [spinalcordtoolbox/spinalcordtoolbox#3587] opened 2021-11-16 22:57 UTC
### Description

matplotlib 3.5 was released 16 hours ago, and (https://matplotlib.org/3.5.0/api/prev_api_changes/api_changes_3.5.0.html#modules)

> The Qt4-based backends, qt4agg and qt4cairo, have been removed. Qt4 has reached its end-of-life in 2015 and there are no releases of either PyQt4 or PySide for recent versions of Python. Please use one of the Qt5 or Qt6 backends.

and this is crashing our tests and blocking CI.

### Steps to Reproduce

0. Install SCT from `master`
1. Run the tests

**Expected behavior:** the tests should pass 

**Actual behavior:**

https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/4231487281?check_suite_focus=true#step:7:28

```
==================================== ERRORS ====================================
___________________ ERROR collecting testing/api/test_gui.py ___________________
ImportError while importing test module '/__w/spinalcordtoolbox/spinalcordtoolbox/testing/api/test_gui.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
python/envs/venv_sct/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
testing/api/test_gui.py:6: in <module>
    from spinalcordtoolbox.gui import base, centerline, sagittal
spinalcordtoolbox/gui/centerline.py:15: in <module>
    from spinalcordtoolbox.gui import widgets
spinalcordtoolbox/gui/widgets.py:10: in <module>
    from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
E   ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg'
=========================== short test summary info ============================
ERROR testing/api/test_gui.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
======================== 25 warnings, 1 error in 5.72s =========================
Error: Process completed with exit code 2.
```

**Comment by kousu** [comment] 2021-11-16 23:02
Question for myself: why are we touching `matplotlib.backends` directly at all? Isn't that supposed to be hidden behind `matplotlib.use()`?

**Comment by kousu** [comment] 2021-11-16 23:11
More direct repro:

```
./install_sct -y
source python/bin/activate && conda activate venv_sct
pytest testing/api/test_gui.py
```

**Comment by kousu** [comment] 2021-11-16 23:14
Okay I've got a fix in but it's an unpleasantly simple one.

**Comment by joshuacwnewton** [comment] 2021-11-16 23:46
Thanks so much for following up on this! Duplicate of #3579, so I'll close that one.

**Closed** 2021-11-17 03:01 UTC

**Comment by kousu** [comment] 2021-11-17 03:03
Durp, I didn't search. :dragon: :sweat_smile:
