### ISSUE TITLE
Discuss relevance in adding SCT templates in https://www.templateflow.org/

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3951] opened 2022-11-18 17:29 UTC

**Comment by joshuacwnewton** [comment] 2022-11-18 17:56
I think this is a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3220?

**Closed by joshuacwnewton** 2022-11-18 17:56 UTC

**Comment by jcohenadad** [comment] 2022-11-18 19:04
> I think this is a duplicate of:

yes it is-- i vaguely remembered opening an issue on this in the past, but i was not sure. I saw a tweet today praising TemplateFlow so i thought it might be a good opportunity for us to be part of this initiative--
