### ISSUE TITLE
Add a method to compute the spinal cord volume

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2707] opened 2020-05-12 19:46 UTC
Several users are asking for a feature to compute spinal cord volume. We could easily implement that in `sct_process_segmentation`.

User posts:
- http://forum.spinalcordmri.org/t/t1-contrast-brain-image-error-output/395/4
- http://forum.spinalcordmri.org/t/get-spinal-cord-volume/152

**Comment by joshuacwnewton** [comment] 2023-01-19 20:29
I'm closing this issue as a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3378, since both issues are focused on adding better ways of computing volume metrics.

**Closed** 2023-01-19 20:30 UTC
Labels: sct_process_segmentation, priority:LOW, feature, good first issue, user requested
