### ISSUE TITLE
Reorienting to RPI (then back) will subtly change the affine matrices by ~1e-4 due to NIFTI orthogonal requirement x2

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4744] opened 2024-12-03 05:40 UTC
### Description

@sandrinebedard discovered that spinal cord and lesion segmentation from the SCIsegV2 model (`sct_deepseg seg_sc_lesion_t2w_sci`) have different qform and sform matrixes than the original image. I can confirm the behaviour by running:

https://github.com/spinalcordtoolbox/sct_tutorial_data/blob/4034ad14637290c915497d8f4ff3bf96a15841a6/single_subject/batch_single_subject.sh#L392:

```console
sct_deepseg -i t2.nii.gz -task seg_sc_lesion_t2w_sci -qc ~/qc_singleSubj
```

Headers diff: https://www.diffchecker.com/2J9FXJou/

Headers:

<details><summary>t2.nii.gz</summary>

```console
sct_image -i t2.nii.gz -header

--
Spinal Cord Toolbox (git-master-64f55fdf022659db5d5c779f01c605d91ca7d052)

sct_image -i t2.nii.gz -header
--

sizeof_hdr	348
data_type	INT16
dim		[3, 64, 320, 320, 1, 0, 0, 0]
vox_units	mm
time_units	s
datatype	4
nbyper		2
bitpix		16
pixdim		[1.0, 0.8, 0.8, 0.8, 1.5, 0.0, 0.0, 0.0]
vox_offset	352
cal_max		0.000000
cal_min		0.000000
scl_slope	1.000000
scl_inter	0.000000
phase_dim	2
freq_dim	1
slice_dim	3
slice_name	Unknown
slice_code	0
slice_start	0
slice_end	0
slice_duration	0.000000
toffset		0.000000
intent		Unknown
intent_code	0
intent_name
intent_p1	0.000000
intent_p2	0.000000
intent_p3	0.000000
qform_name	Scanner Anat
qform_code	1
qto_xyz:1	0.799726 0.000000 -0.020942 -19.452049
qto_xyz:2	0.000000 0.800000 0.000000 -115.151794
qto_xyz:3	0.020942 -0.000000 0.799726 -122.996811
qto_xyz:4	0.000000 0.000000 0.000000 1.000000
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
sform_name	Scanner Anat
sform_code	1
sto_xyz:1	0.799726 0.000000 -0.020942 -19.452049
sto_xyz:2	0.000000 0.800000 0.000000 -115.151794
sto_xyz:3	0.020942 -0.000000 0.799726 -122.996811
sto_xyz:4	0.000000 0.000000 0.000000 1.000000
sform_xorient	Left-to-Right
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
file_type	NIFTI-1+
file_code	1
descrip		TE=1.2e+02;Time=110001.045;phase=1
aux_file	imgComments
```

</details>

<details><summary>t2_lesion_seg.nii.gz </summary>

```console
sct_image -i t2_lesion_seg.nii.gz -header

--
Spinal Cord Toolbox (git-master-64f55fdf022659db5d5c779f01c605d91ca7d052)

sct_image -i t2_lesion_seg.nii.gz -header
--

sizeof_hdr	348
data_type	UINT8
dim		[3, 64, 320, 320, 1, 1, 1, 1]
vox_units	mm
time_units	s
datatype	2
nbyper		1
bitpix		8
pixdim		[1.0, 0.8, 0.8, 0.8, 1.0, 1.0, 1.0, 1.0]
vox_offset	352
cal_max		0.000000
cal_min		0.000000
scl_slope	1.000000
scl_inter	0.000000
phase_dim	2
freq_dim	1
slice_dim	3
slice_name	Unknown
slice_code	0
slice_start	0
slice_end	0
slice_duration	0.000000
toffset		0.000000
intent		Unknown
intent_code	0
intent_name
intent_p1	0.000000
intent_p2	0.000000
intent_p3	0.000000
qform_name	Scanner Anat
qform_code	1
qto_xyz:1	0.799726 0.000000 -0.020939 -19.452053
qto_xyz:2	0.000000 0.800000 0.000000 -115.151794
qto_xyz:3	0.020939 -0.000000 0.799726 -122.996651
qto_xyz:4	0.000000 0.000000 0.000000 1.000000
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
sform_name	Scanner Anat
sform_code	1
sto_xyz:1	0.799726 0.000000 -0.020939 -19.452053
sto_xyz:2	0.000000 0.800000 0.000000 -115.151794
sto_xyz:3	0.020939 -0.000000 0.799726 -122.996651
sto_xyz:4	0.000000 0.000000 0.000000 1.000000
sform_xorient	Left-to-Right
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
file_type	NIFTI-1+
file_code	1
descrip		TE=1.2e+02;Time=110001.045;phase=1
aux_file	imgComments
```

</details>

(I tried `sct_deepseg seg_sc_lesion_t2w_sci` also on another subject (`sub-zh01_ses-01_acq-sag_T2w.nii.gz`), and the qform and sform matrices are also different!)

**Comment by joshuacwnewton** [comment] 2024-12-03 13:10
> https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4697

The diff seems relatively small (~1e-4), so I would suspect that this is related to nibabel's behavior that sets the `qform` equal to the "closest orthogonal matrix":

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4689#issuecomment-2474539772
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4697

(Given that a lot of our processing involves reorientation, and reorientation involves setting the sform/qform, this "orthogonal" substep seems somewhat unavoidable?)

----

Note: I noticed that even before I made the above change, the qform/sform would change subtly between steps due to nibabel's "closest orthogonal matrix" step anyway, so this may not even be new? (It could be that you're just noticing it now...)

**Comment by joshuacwnewton** [comment] 2024-12-03 13:15
To avoid even this subtle change, we may want to preserve the original header of the input image, then reassign it to the output image. That way, we don't lose precision when reorienting to RPI (qform -> orthogonal) then reorienting back (qform -> orthogonal again)?

**Comment by joshuacwnewton** [comment] 2024-12-03 13:23
If I add the following code to the postprocessing in the `segment_non_ivadomed` function:

```
            # 5. Preserve the affine matrix of the input image
            im_out.copy_affine_from_ref(Image(fname_in))
```

If I do this, then I can get the affine to stay the same: [diffchecker](https://www.diffchecker.com/d1axSqXo/)

**Comment by joshuacwnewton** [comment] 2024-12-03 13:37
> Though I'm curious how critical a difference of 1-e4 magnitude is to further processing?

To answer this question, I tried generating two copies of the output, one with the identical affine and one with the subtly changed affine, then viewing them in FSLeyes to see if there are noticeable differences.

The warning it generates is the following:

![image](https://github.com/user-attachments/assets/47e95abe-2cc2-425b-8f31-1928c233da6e)

> Images have different orientations/fields of view - alignment/orientation labels may be incorrect!

Also, when comparing sample scanner/anatomical coordinates to voxel coordinates before and after the fix (in separate `fsleyes` windows), I see the following:

`t2_sc_seg.nii.gz`:

![image](https://github.com/user-attachments/assets/14e8c71c-61b3-4117-b672-ed09f9d0337a)

`t2_sc_seg_with_fix.nii.gz`:

![image](https://github.com/user-attachments/assets/5c8d4fc0-725f-4c57-8d66-822ff19ac6db)

So yes, the `1e-4` change in the affine does make a significant difference, and we should make attempts to ensure that these small changes don't propagate.

**Comment by joshuacwnewton** [comment] 2024-12-03 13:57
Just to double-check that #4697 really is the cause, if I try reverting the change, then re-running segmentation, I can indeed generate the same affine...

Given that the change made in #4697 is rather universal, I'm a bit worried that this affine diff is present in pretty much all of our functions that A) reorient to RPI and back and B) produce output in the same space as the original input image. Meaning, we may need the "copy affine from input" fix in many places if we truly wish to implement #4697. :sweat: 

I am wondering if it would be better to revert the changes in #4697, but make our `check_affines_match` test looser instead, to avoid the crash while still preserving the results of the output? It would maybe result in sform/qform diffs, but it would at least avoid significant numerical changes between SCT versions. :sweat: 

tagging @jcohenadad and @mguaypaq for input

**Closed** 2024-12-03 16:50 UTC
Labels: bug, sct_deepseg
