### ISSUE TITLE
Installation failed Permission denied on .bash_profile

### ISSUE THREAD

**Issue by tzebre** [spinalcordtoolbox/spinalcordtoolbox#4099] opened 2023-04-22 00:00 UTC
When running `./install_sct` got this Error message: 

```
Darwin Sansfil-Eduroam-Externe-213-192.polymtl.ca 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
ProductVersion:		13.1
./install_sct: line 255: /Users/theomathieu/.bash_profile: Permission denied
```

I solved this problem by running `sudo ./install_sct` instead of `./install_sct`

**Additional info** 
First lines of `sct_check_dependencies`
```
--
Spinal Cord Toolbox (git-master-32501697eecf9678edb928b0a2c16971f9ec3257)

sct_check_dependencies 
--


SYSTEM INFORMATION
------------------
SCT info:
- version: git-master-32501697eecf9678edb928b0a2c16971f9ec3257
- path: /Users/theomathieu/Documents/Stage/Code/spinalcordtoolbox
OS: osx (macOS-10.16-x86_64-i386-64bit)
CPU cores: Available: 8, Used by ITK functions: 8
RAM: Total: 16384MB, Used: 1282MB, Available: 831MB

OPTIONAL DEPENDENCIES
---------------------
Check FSLeyes version...............................[  ]
   (127, '/bin/sh: fsleyes: command not found')
...
```

**Comment by joshuacwnewton** [comment] 2023-04-24 13:59
Thank you so much for reporting this issue! I believe this might be a duplicate issue of:

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3622

We haven't yet settled on a solution for that issue, because as @kousu stated in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3622#issuecomment-992715247:

> `.bash_profile` should always be readable; if it's not, it should just be deleted. That file is really really meant for a user to customize their environment, and if this user accidentally `chmod 000`'d their startup script then I think that's a bug on their system we can help them correct, not something we should try to workaround in our system.

I'm glad you were able to solve your problem with `sudo`, though in the future, you may want to take a look at the permissions on your `.bash_profile` file as well.

(Closing this issue as a duplicate of #3622.)

**Closed by joshuacwnewton** 2023-04-24 13:59 UTC

**Comment by mguaypaq** [comment] 2023-04-24 14:05
Although, I would expect that using `sudo` with the installer might create different problems down the line? Like, is the SCT installation itself owned by `root` in that case? Which is fine if the installation is in a "global" location, but if it lives inside the user's home that might not be great.

Since @tzebre is a lab member, I'll follow up in-person for faster debugging.
