### ISSUE TITLE
Separate labels with different values are being merged together in the QC report for `-p sct_label_vertebrae`

### ISSUE THREAD

**Issue by yw7** [spinalcordtoolbox/spinalcordtoolbox#4379] opened 2024-02-20 21:56 UTC
Hello SCT team,

I'm reaching out to suggest an enhancement for the sct_qc that could greatly improve the visualization of multi-label segmentations.

When leveraging `-p sct_label_vertebrae` for multiple labeled segmentations in the sct_qc, there seems to be an issue where labels are merged together, resulting in a visual representation that lacks the necessary distinction between different segmented areas. This presents a challenge when evaluating the precision of vertebral labeling, where clear and distinct colors for each label are essential to accurately differentiate adjacent anatomical structures.

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/36595323/33c9cf10-c928-4dbe-b14a-937a3e0e46da)

I propose the implementation of a feature that allows sct_qc to automatically assign distinct colors to each label in multi-label segmentations. Ideally, this could be enabled through a command like `sct_qc -i <nii_image> -s <nii_seg> -p multi_label -plane sagittal`, which would generate a color-coded overlay where each label is clearly distinguishable.

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/36595323/8bdd9d0d-793b-4c53-bcbc-2b47f59352fb)

Thank you so much!

Best,

Yehuda

**Comment by joshuacwnewton** [comment] 2024-02-20 22:24
Could you please share a sample segmentation that is producing this behavior? (Both `-i` and `-s` if possible, so that I can run the `sct_qc` command.) You can reach out to me on Slack to share the data if you need to, as well.

This seems like it may be a bug more than anything -- I'm surprised to see that adjacent labels with different values are being merged as one label. (Though I'd want to double-check by debugging the code.) :)

**Comment by yw7** [comment] 2024-02-20 22:37
Here is the data:

-i [multi_amu01_T1w_0000.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/14351872/multi_amu01_T1w_0000.nii.gz) -s [multi_amu01_T1w.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/14351873/multi_amu01_T1w.nii.gz)

Thanks!!
Best,
Yehuda

**Comment by joshuacwnewton** [comment] 2024-02-23 21:16
I can confirm that this is a relatively straightforward bug:

- The label image that you're working with has 20 different labels:
   - 200/201: Spinal cord and CSF
   - 217/218/219/220/221/222/223/224: Intervertebral discs
   - 32/33/34/35/36/37/38/39/40/41: Vertebrae
- These values are interspersed (in other words, the label values do not appear sequentially from superior to inferior). You might get, say, labels 32 -> 217 -> 33 -> 218 next to one another, since the discs and vertebrae are interleaved.
- This is different from the traditional vertebral level labels, which appear sequentially in order of vertebrae (2, 3, 4, etc.)
- The colormap we use was designed with high-contrast colors in mind. We start with a base of 7 colors, then repeat them sequentially, which works fine for our usual vertebral labels:
    https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/e3d00c58cbe98e615e469c63edcd6693f3a0004d/spinalcordtoolbox/reports/qc.py#L52-L60
- But, due to the large number of labels + interspersed values + large gaps between groupings of label values, the current coloring approach does not work for these labels.

To fix this, I just need to think of a way to assign colors to label values that does not result in repeated label colors for your image. For example, maybe we split the labels up into subgroups (as I did above). Then, the grouping of {32:41} gets only alternating "warm" colors, and the grouping of {217:224} gets only alternating "cool" colors, etc. :thinking:

**Comment by joshuacwnewton** [comment] 2024-02-23 21:27
I was able to quickly add a (partial fix): 

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/716c9d4a-d486-4e42-91ea-9550206fcbe1)

This fixes the big issue of "identical colors being used for adjacent (sequential) labels". However, there is still the minor issue that the color used for the CSF (label 201) will sometimes match the color of adjacent vertebrae (e.g. 217:224). This is because we repeat the colors across the "groups" of labels, which is why I suggested splitting up the groups into subsets of color. 

I will try the more complex fix next. :)

**Comment by joshuacwnewton** [comment] 2024-02-23 22:27
How about this?

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/28cc08e0-14da-43f1-9432-c3f471f3a084)

Here, we split the labels into distinct color groups (reds, blues, greens, oranges, purples), then within these color groups, we alternate between intensities.

In this case:

- Cord/CSF were assigned "blues"
- Vertebrae were assigned "reds"
- Discs were assigned "greens"

**Comment by jcohenadad** [comment] 2024-02-23 23:06
This is very nice! I'm wondering how we should standardize our color mapping across functions. Eg: in other functions (eg: sct_deepseg_sc), the spinal cord appear red in the QC report. Same for the vertebral labeling, each level has its own color.

**Comment by joshuacwnewton** [comment] 2024-02-24 01:28
The tricky thing is that, unless the exact label values are standardized, it would be hard to directly assign color maps to specific features.

Unless, are the label values here ones that we expect to consistently use for spinal cord/CSF/vertebrae?

**Comment by yw7** [comment] 2024-02-24 06:49
Hi @joshuacwnewton, thank you for your assistance!

I'm uncertain if this is the optimal practice, but one alternative method could involve utilizing a random color assignment as follows:
```python
unique_labels = np.unique(image).astype(int)
colors = {}
for label in unique_labels:
    np.random.seed(label)  # Seed with label for reproducibility
    colors[label] = np.random.randint(0, 255, 3)  # Generate a random color
```

**Comment by jcohenadad** [comment] 2024-02-24 16:15
I'm not a big fan of random colors-- using a color code for label number can help QCing more rapidly

**Comment by yw7** [comment] 2024-02-24 16:24
Even if the color remains consistent for a specific label?
Using `rs = np.random.RandomState(np.random.MT19937(np.random.SeedSequence(label)))` with the label ensures color consistency for that specific label.

**Comment by joshuacwnewton** [comment] 2024-02-24 19:28
> Your solution outlined in [#4379 (comment)](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4379#issuecomment-1962084303) looks very promising! I'm curious about how it will be implemented. Will it detect the groups automatically, or will it require an extra parameter?

My prototype code in my test branch is currently detecting the groups automatically:

<details>

```python
    def _assign_label_colors(self, labels):
        """
        This function ensures that each label is assigned a distinct color,
        while also separating groups of labels into visually distinct subsets of colors.
        """
        # Arrange colormaps for max contrast between colormaps, and max contrast between colors in colormaps
        distinct_colormaps = ['Reds', 'Blues', 'Greens', 'Oranges', 'Purples']
        colormap_sampling = [0.25, 0.5, 0.75, 0.5]  # light -> medium -> dark -> medium -> (repeat)

        # Split labels into subgroups --> we split the groups wherever the difference between labels is > 1
        start_end = [0, len(labels)]
        for idx, (prev, curr) in enumerate(zip(labels, labels[1:]), start=1):
            if curr - prev > 1:
                start_end.insert(len(start_end)-1, idx)
        label_groups = [labels[start:end] for start, end in zip(start_end, start_end[1:])]

        label_colors = {}
        # Assign a colormap to each group of labels (while sampling the colormap at different points)
        for i, label_group in enumerate(label_groups):
            # if there's only 1 group of labels, use colors spanning the whole spectrum
            if len(label_groups) == 1:
                colors = self._high_contrast_colors
            # otherwise, make sure each group of labels gets a distinct set of colors from a specific colormap
            else:
                colormap = cm.get_cmap(distinct_colormaps[i % len(distinct_colormaps)])
                colors = [color.to_hex(c) for c in [colormap(n) for n in colormap_sampling]]

            # Then, assign the colors to each sequential label within the group
            for j, label in enumerate(label_group):
                label_colors[label] = colors[j % len(colors)]

        return label_colors
```

</details>

> Even if a specific label always appears in the same color?

If we can assume that a specific label value will be consistently used for a given feature (e.g. 200 == spinal cord), and if we already have a specific color scheme in mind for specific labels (e.g. spinal cord == red, vertebrae = rainbow), then it seems to me that @jcohenadad's suggestion [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4379#issuecomment-1962116261) would be preferable to random colors?

(The only reason I suggested automatically assigning colors is if we can't assume label values will be used consistently.)

**Comment by yw7** [comment] 2024-02-24 20:01
Yes definitely, you’re right. if you know the labels:anatomy in advance better to have the colors set for greater contrast for anatomically close structures.

**Comment by joshuacwnewton** [comment] 2024-02-27 18:56
For some reason, GitHub isn't letting me request your review on PR #4383, so I'm tagging you here @yw7. :blush:

**Comment by yw7** [comment] 2024-02-27 21:26
Work great for me (: Thank you!!!!
![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/36595323/6d214564-297c-4c6b-b810-934f5fd70e1a)

About this, will it be possible to remove the labels?

> Another issue is the vertebrae names (C1, C2, etc.), will there be an option to disable those for general multi-label segmentation? or using `-p <some new option>` instead of `-p sct_label_vertebrae` to disable it?

**Closed** 2024-03-14 19:27 UTC
Labels: bug, sct_qc
