### ISSUE TITLE
Automate Releases

### ISSUE THREAD

**Issue by kousu** [spinalcordtoolbox/spinalcordtoolbox#3163] opened 2021-01-12 21:58 UTC
We have this pretty long release engineering process here: https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release

It's pretty fiddly and bug-prone. We can probably do a lot better by moving most of it into Github Actions.

It should be possible to just click "Release" and have it do all the right things.

1. Compute all the PRs merged since the last release and verify they have been tagged with the proper Milestone
2. Generate the changelog
3. Verify the current commit has been tested and passed a "nightly" CI run
4. Merge to the release branch?

**Comment by joshuacwnewton** [comment] 2021-01-12 22:14
In our discussion during the SCT dev meeting, we mentioned that because `batch_processing.sh` is used as a manual check before submitting a new release, it might be a blocker for automating releases.

Since @Drulex was a big part of discussion in #2888, I'm tagging here.

**Comment by kousu** [comment] 2021-01-12 22:16
To be honest, this is going to be on my backburner unless I can pair with someone, so I'm inviting @anhil187, @drulex, and @joshuacwnewton to take a look at this with me. Any of you game?

**Comment by kousu** [comment] 2021-01-12 22:17
> In the SCT dev meeting it was mentioned that because `batch_processing.sh` is used as a manual check before submitting a new release, it might be a blocker for automating releases.
> 
> Since @Drulex was a big part of discussion in #2888, I'm tagging here.

Julien doesn't think there's a safe way to automate comparing the numbers, but we can at least move it to cron so that we have a ready point of reference; maybe we can even make up some sort of badge or auto-committed "last output" file, which can then be automatically pulled into the changelog.

**Comment by kousu** [comment] 2021-01-12 22:21
I don't know about the `release` branch. When you click "Release" on Github you have to pick a branch/commit/tag to point it to, so it would be awkward to then take that commit and merge it to a separate branch and then what, maybe edit the release object using an Action to point it at the new commit?

We're keeping `release` around because there's some things in `master` that were taken out a long time ago, but mostly they're cruft and I don't think we're using them. It would be a lot more straightforward if we could just do releases from `master`.

**Comment by jcohenadad** [comment] 2021-01-12 22:27
> To be honest, this is going to be on my backburner unless I can pair with someone, so I'm inviting @anhil187, @Drulex, and @joshuacwnewton to take a look at this with me. Any of you game?

also tagging @charjl and @gisellemartel

**Comment by kousu** [comment] 2021-01-12 22:29
Yes please! The more the merrier on this one.

**Comment by kousu** [comment] 2021-01-12 22:40
Some ideas:

* https://github.com/marketplace/actions/release-drafter
* https://github.com/marketplace/actions/create-a-release (this one is more for; ; we could use this to keep the `release` branch around, I suppose, if we picked a different trigger)
* https://github.com/marketplace/actions/release-please-action - triggered by making a commit with a particular pattern in it
* https://github.com/marketplace/actions/release-generator
* https://github.com/marketplace/actions/release-me
* https://github.com/marketplace/actions/automatic-releases

There's a ton more too.

**Comment by Drulex** [comment] 2021-01-13 13:45
> To be honest, this is going to be on my backburner unless I can pair with someone, so I'm inviting @Drulex, and @joshuacwnewton to take a look at this with me. Any of you game?

I'm game, however I think that this discussion is also related to the packaging discussion in the sense that any code developed for this will be tightly coupled to the packaging scheme (which right now is a custom scheme).

**Comment by joshuacwnewton** [comment] 2021-01-21 17:03
> We have this pretty long release engineering process here: https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release

I've created a [Google Doc](https://docs.google.com/document/d/18ePk75oe8XagLYdjrsB45h_ob0OJE5kTqooCK8wPtzA/edit?usp=sharing) so that it's a little easier to comment directly alongside the steps themselves.

In that doc, I've highlighted the non-CLI steps that currently require manual intervention. Feel free to add comments. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment] 2021-01-21 17:20
> It should be possible to just click "Release" and have it do all the right things.

Something  just learned about: To manually trigger a workflow in GitHub Actions, the [`workflow_dispatch`](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) event can be used.

**Comment by joshuacwnewton** [comment] 2021-01-23 19:47
> It should be possible to just click "Release" and have it do all the right things.

Right now, in our current steps, we're more or less using a 3-step process:

1. Updating `CHANGES.md`. 
    * Checking labels/milestones
    * Running `changelog`
    * Creating a PR on master to review the updated file.
2. Setting up and testing the release branch.
    * Merging `master` into `release`.
    * Updating `requirements-freeze.txt`
    * Updating `version.txt`
    * Testing the release branch (`batch_processing.sh`, CI w/ `requirements-freeze.txt` install)
3. Creating the release itself on GitHub.

Each of these steps could be automated individually, but, as of right now, I can't think of a safe way of combining the steps.

(One thing to note, though, is that if/when #3140 and #2888 are addressed, testing the release branch may become redundant -- the testing could be done via the changelog PR to master instead. So, that might allow us to combine 2) and 3), making overall process two steps instead.)

**Comment by jcohenadad** [comment] 2021-01-23 20:12
this is already a *huge* improvement, thank you @joshuacwnewton !

**Comment by joshuacwnewton** [comment] 2021-01-23 20:14
Ah, I haven't done anything yet! I was just giving an overview of places for potential improvements. 🙂 
 
But, now that v5.1.0 is released, I would be happy to look into putting these proposed changes into place.

**Comment by joshuacwnewton** [comment] 2021-03-07 17:07
> 1. Updating `CHANGES.md`.
>     * Checking labels/milestones
>     * Running `changelog`
>     * Creating a PR on master to review the updated file.
>     * The PR for the changelog is also a convenient time to test `master` via CI (`batch_processing.sh`, pytest).

Update: This section has been handled by #3264 and #3198. Once both of those PRs are merged, only 2) and 3) remain.

**Comment by kousu** [comment] 2021-04-06 19:33
I found https://riggaroo.dev/using-github-actions-to-automate-our-release-process/ helpful for figuring out how to do [this](https://github.com/sct-data/spinalcordtoobox-data-template/blob/1724d1866583e1d98bf5afc096059a02851f52d4/.github/workflows/release.yml). But it seems like you're sort of already on top of this even without that!!

**Comment by kousu** [comment] 2021-04-06 19:40
In passing, `requirements-freeze.txt` and `version.txt` conflict with my vision for #1526.

`version.txt` should be just `setup(..., version=...)` IMO, which we can read back with `importlib.metadata.distribution('spinalcordtoolbox').version`. That's the py3k way to do that afaict.

And `requirements-freeze.txt` conflicts with making a pip-installable package because it forces you to `pip install -r requirements.txt` and you can't use list SCT as a dependency in other software that way -- not without copying our `requirements-freeze.txt` into your app.

And actually why do we need a `release` branch anyway? As far as I can tell, it's just because there are some scattered large files in the repo that we *don't* want to package, that were `git rm`d a long time ago from `release` but not from `master`; but if we make a more proper pip package we can just *tell* it what files to skip with `exclude=` or with #3161. So I think step 2 can become a lot shorter (probably...as short as [what I'm doing for the dependencies](https://github.com/sct-data/spinalcordtoobox-data-template/blob/1724d1866583e1d98bf5afc096059a02851f52d4/.github/workflows/release.yml)) if we get to #1526 .

Which do you think will take longer? :P

**Comment by joshuacwnewton** [comment] 2021-05-06 14:24
> `version.txt` should be just `setup(..., version=...)` IMO, which we can read back with `importlib.metadata.distribution('spinalcordtoolbox').version`. That's the py3k way to do that afaict.

This is doable!

> And `requirements-freeze.txt` conflicts with making a pip-installable package because it forces you to `pip install -r requirements.txt` and you can't use list SCT as a dependency in other software that way -- not without copying our `requirements-freeze.txt` into your app.

requirements-freeze.txt is for the benefit of our regular users (who won't be building apps on top of SCT), so that they can install a specific version of SCT and trust that the results are are reproducible no matter when they install it. 

But, you're right, there's a better way of doing this. Once SCT is pip installable, we can stop including `requirements-freeze.txt` inside the package, and instead distribute a versioned `requirements.txt` file as a separate file on each GitHub Release. 

That way, if somoene want to install a specific version of SCT with pinned dependencies, they can download the file from the Release page and `pip install -r requirements-X.Y.Z.txt` into a venv. That way, the main package on PyPI would be unaffected.

> And actually why do we need a release branch anyway? 

The main difference between `release` and `master` is that `release` has a requirements-freeze.txt file. In other words, it makes it so that requirements-freeze.txt is only present in the downloads from the Release page (and nowhere else).

But, I agree that this would no longer be necessary if we do things as described above.

**Closed** 2021-06-23 14:37 UTC
