### ISSUE TITLE
Empty prediction for `-task seg_sc_lesion_t2w_sci` when using `nnunetv2==2.4.2`

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4556] opened 2024-07-08 15:13 UTC
### Description

Running `sct_deepseg -task seg_sc_lesion_t2w_sci` on a sample T2w image (Dropbox [link](https://www.dropbox.com/scl/fi/czg2mgc07ytxpf6g086m1/sub-2416B6027B_ses-2416B_T2w.nii.gz?rlkey=ucdxljro3hn7tlbq0bti40uab&dl=0)) results in an empty spinal cord prediction:

```bash
$ sct_deepseg -i sub-2416B6027B_ses-2416B_T2w.nii.gz -task seg_sc_lesion_t2w_sci


--
Spinal Cord Toolbox (git-master-65e44b5068fe5d8a094e3e0571566c01d2d460ab)

sct_deepseg -i sub-2416B6027B_ses-2416B_T2w.nii.gz -task seg_sc_lesion_t2w_sci
--

Model 'model_seg_sci_multiclass_sc_lesion_nnunet' is up to date (Source: https://github.com/ivadomed/model_seg_sci/releases/download/r20240130/model-sci-multisite_r20240130.zip)
...
```

<details><summary>screenshot</summary>

<img width="700" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/39456460/676d64bf-a51f-448f-9219-c4be9e90d4f7">

</details>

However, when downloading the model from [its source](https://github.com/ivadomed/model_seg_sci/releases/tag/r20240130) and running the prediction using the [run_inference_single_subject.py](https://github.com/ivadomed/model_seg_sci/blob/main/packaging/run_inference_single_subject.py) script, the spinal cord segmentation is fine!

```bash
$ conda activate nnunet
$ python ~/code/model_seg_sci/packaging/run_inference_single_subject.py -i sub-2416B6027B_ses-2416B_T2w.nii.gz -path-model ~/Downloads/model-sci-multisite_r20240130 -pred-type sc -o sub-2416B6027B_ses-2416B_T2w_seg.nii.gz
```

<details><summary>screenshot</summary>

<img width="700" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/39456460/4acfc7c5-889f-4acc-8274-3e517c2c7cda">

</details>

**Comment by valosekj** [comment] 2024-07-08 15:54
Some first debugging: setting a breakpoint right after the nnunet prediction (to L270 in `deepseg/inference.py`) to see what the prediction looks like before any post-processing.

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/65e44b5068fe5d8a094e3e0571566c01d2d460ab/spinalcordtoolbox/deepseg/inference.py#L264-L270

The prediction is already empty here:

<img width="400" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/39456460/1a4f0e0b-12d9-4615-b028-7f01203d91e1">

**Comment by valosekj** [comment] 2024-07-08 16:41
One important difference between `sct_deepseg` and [run_inference_single_subject.py](https://github.com/ivadomed/model_seg_sci/blob/main/packaging/run_inference_single_subject.py) is the nnunet predictor. 

`sct_deepseg` uses `predict_single_npy_array`:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/65e44b5068fe5d8a094e3e0571566c01d2d460ab/spinalcordtoolbox/deepseg/inference.py#L264

while [run_inference_single_subject.py](https://github.com/ivadomed/model_seg_sci/blob/main/packaging/run_inference_single_subject.py) uses `predict_from_files`:

https://github.com/ivadomed/model_seg_sci/blob/5d0886ce3af575643313463db1b8a6ab60890cf5/packaging/run_inference_single_subject.py#L186

**Comment by joshuacwnewton** [comment] 2024-07-08 18:42
I am able to reproduce the issue, both on `master` and on 6.2/6.3.

> [!NOTE]
> We do have a passing test (with GT comparisons) for this model already, so we at least have demonstrated that `predict_single_npy_array` _can_ work OK:
>
> https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/ecea2beaadc67ec7c02f6b539592db3bc01a1495/testing/cli/test_sct_deepseg.py#L133-L140

I tried a lot of different things (comparing resolutions, orientations, different inference functions, cropped images vs. full anat, etc.) and I had some theories about what the problem might be, however I didn't find any big revelations.

One thing I did find, though: I copied the `run_inference_single_subject.py` into the SCT folder, then ran the script using the SCT venv. 

```
run_inference_single_subject.py -i sub-2416B6027B_ses-2416B_T2w.nii.gz 
                                -o script-pred.nii.gz 
                                -path-model /home/joshua/repos/spinalcordtoolbox/data/deepseg_models/model_seg_sci_multiclass_sc_lesion_nnunet/ 
                                -pred-type sc
```


And... I still got the same empty output! (Top files are SCT output, bottom file is script output.)

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/0e478c5e-f9ca-4411-b84a-e5b4b1cf640a)

Just to check, then -- @valosekj could you share details about how you were able to get a proper SC seg from the script? (Which version of the model, which version of the conda packages, etc.) Maybe it is a dependency issue, rather than a code issue? :thinking:

**Comment by valosekj** [comment] 2024-07-08 20:06
> And... I still got the same empty output! 

Interesting!

> Just to check, then -- @valosekj could you share details about how you were able to get a proper SC seg from the script? (Which version of the model, which version of the conda packages, etc.) Maybe it is a dependency issue, rather than a code issue? 🤔

Sure! Here is the exact command:

```bash
python ~/code/model_seg_sci/packaging/run_inference_single_subject.py
    -i sub-2416B6027B_ses-2416B_T2w.nii.gz
    -path-model ${SCT_DIR}/data/deepseg_models/model_seg_sci_multiclass_sc_lesion_nnunet 
    -pred-type sc 
    -o sub-2416B6027B_ses-2416B_T2w_seg.nii.gz
```

I'm using the exact same model as you (`${SCT_DIR}/data/deepseg_models/model_seg_sci_multiclass_sc_lesion_nnunet`).

I have just tried the command with two different conda envs, and I think we've found a potential culprit!!!
- SCT's `venv_sct` conda env - empty prediction
- my local `nnunet` conda env - a good prediction!!!

[Here](https://www.diffchecker.com/cTqAxBcl/) is the comparison of the packages from both envs. Both `nnunet` and `torch` have different versions between the envs:

```bash
(venv_sct) valosek@macbook-pro:~/code/sct$ pip freeze | grep nnunet
nnunetv2==2.4.2
(venv_sct) valosek@macbook-pro:~/code/sct$ pip freeze | grep torch
torch==2.2.0

valosek@macbook-pro:~/code/sct_nnunet$ conda activate nnunet
(nnunet) valosek@macbook-pro:~/code/sct_nnunet$ pip freeze | grep nnunet
nnunetv2==2.4.1
(nnunet) valosek@macbook-pro:~/code/sct_nnunet$ pip freeze | grep torch
torch==2.3.1
```

**Comment by joshuacwnewton** [comment] 2024-07-08 20:44
Ah! Right off the bat, I can explain why `torch` is being held back in SCT's venv -- this came up in the "torchio" sub-issue contained within:

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4535

**Comment by joshuacwnewton** [comment] 2024-07-08 21:39
Aha! This is precisely due to `nnunvet2==2.4.2` -- downgrading to `2.4.1` in my SCT venv (without reinstalling other dependencies) results in a proper segmentation for the inference script. However, downgrading causes an error for `sct_deepseg`:

```
    image, seg_prev_stage, props, ofname = self._data[idx][0]
ValueError: not enough values to unpack (expected 4, got 1)
```

This is the same error that I reported upstream in:

- https://github.com/MIC-DKFZ/nnUNet/issues/2112

If I manually fix the bug in my local copy of 2.4.1 (using the fix that got merged upstream), then re-run inference, I get the exact same (proper) SC seg! :tada: 

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/115fe826-b68b-4185-a31c-dbaa7147f2cd)

This leaves us with quite the dilemma! If we downgrade to 2.4.0/2.4.1, we run into another bug. If we upgrade to 2.4.2, we run into this empty segmentation issue. 2.3.1 seems to be the newest version that runs successfully. :thinking:

**Comment by valosekj** [comment] 2024-07-16 15:52
> If I manually fix the bug in my local copy of 2.4.1 (using the fix that got merged upstream), then re-run inference, I get the exact same (proper) SC seg! 🎉

Yes! This is also working for me! Thanks!
Namely, I did the following:

```bash
# activate SCT conda env (`venv_sct `)
source ${SCT_DIR}/python/etc/profile.d/conda.sh
conda activate venv_sct

# downgrade nnunetv2 to 2.4.1
pip install nnunetv2==2.4.1

# edit data_iterators.py according to https://github.com/MIC-DKFZ/nnUNet/pull/2114/files
cd $SCT_DIR
nano ./python/envs/venv_sct/lib/python3.9/site-packages/nnunetv2/inference/data_iterators.py
```

**Comment by joshuacwnewton** [comment] 2024-07-18 15:55
2.3.1 works for me as well. I'll open a PR. :)

**Comment by joshuacwnewton** [comment] 2024-11-18 17:05
I am reopening this issue because it appears that TotalSpineSeg needs version 2.4.2. I will try to get to the bottom of why this update causes an empty prediction.

**Comment by joshuacwnewton** [comment] 2024-11-18 17:19
Ahh!! Good news! There is a new release after 2.4.2 (2.5.1) that results in a non-empty segmentation. :tada:

**Closed** 2024-11-18 19:39 UTC
Labels: bug, priority:HIGH, sct_deepseg
