### ISSUE TITLE
Variable "new_size" has wrong dimensions during resampling with flag -f on 4D images

### ISSUE THREAD

**Issue by PaulBautin** [spinalcordtoolbox/spinalcordtoolbox#3409] opened 2021-06-04 19:08 UTC
### Description

When resampling image with sct_resample and flag -f on a 4D image, the folowing error is displayed:
```
--
Spinal Cord Toolbox (git-master-a685d7f0d8032f9df685a08d22947947ac416e71)

sct_resample -i fmri.nii.gz -f 2
--

load data...
Traceback (most recent call last):
  File "/home/paul/Github/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_resample.py", line 155, in <module>
    main(sys.argv[1:])
  File "/home/paul/Github/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_resample.py", line 150, in main
    param.interpolation, param.verbose, fname_ref=param.ref)
  File "/home/paul/Github/spinalcordtoolbox/spinalcordtoolbox/resampling.py", line 156, in resample_file
    nii_r = resample_nib(nii, new_size.split('x'), new_size_type, image_dest=nii_ref, interpolation=interpolation)
  File "/home/paul/Github/spinalcordtoolbox/spinalcordtoolbox/resampling.py", line 71, in resample_nib
    shape_r = tuple([int(np.round(shape[i] * float(new_size[i]))) for i in range(img.ndim)])
  File "/home/paul/Github/spinalcordtoolbox/spinalcordtoolbox/resampling.py", line 71, in <listcomp>
    shape_r = tuple([int(np.round(shape[i] * float(new_size[i]))) for i in range(img.ndim)])
IndexError: list index out of range
```

### Steps to Reproduce

With 4D image: [fmri.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/6600575/fmri.zip)
run code: `sct_resample -i fmri.nii.gz -f 2`

**Expected behavior:** A 4D resampled image in output

**Actual behavior:** The error is due to the lines in `spinalcordtoolbox/resampling.py`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a685d7f0d8032f9df685a08d22947947ac416e71/spinalcordtoolbox/resampling.py#L60-L71

When using flag -f in sct_resample the variable `new_size` is an integer. Therefore:

- if the input image is 4D,  `len(new_size)=3` is different than `img.ndim=4`  when computing new shape `shape_r`. 

 - It is not an issue for 3D images because in that case `len(new_size) = img.ndim = 3` after `new_size = tuple([new_size[0] for i in range(img.ndim)])`

### Solution
Make sure that when new_size_type is "factor" and image is 4D that new_size is of the right dimensions.

**Comment by joshuacwnewton** [comment] 2022-06-06 15:40
This issue has the same root cause as https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3552, and so it was fixed by https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3553.

Now, the above example code runs successfully without error:

```console
> sct_resample -i fmri.nii.gz -f 2

--
Spinal Cord Toolbox (git-master-afac95d7a205b9017eff37162db8048653bcc1ce)

sct_resample -i fmri.nii.gz -f 2
--

load data...

Done! To view results, type:
itk-snap -g fmri_r.nii.gz
```

**Closed by joshuacwnewton** 2022-06-06 15:40 UTC
Labels: bug, sct_resample, API: resampling.py
