### ISSUE TITLE
`sct_process_segmentation -perslice 1` - include `VertLevel` information across all available levels

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#3976] opened 2022-12-06 22:19 UTC
### Description

When running `sct_process_segmentation -perslice 1`, is it possible to include the `VertLevel` information across all available levels?

I intuitively thought that it could have been possible by running:

```
sct_process_segmentation -i t1w_seg-manual.nii.gz -perslice 1 -vertfile t1w_seg-manual_labeled.nii.gz
```

However, the output `csa.csv` file has an empty `VertLevel` column:

```
Timestamp              SCT Version                                             Filename                                                                              Slice (I->S)  VertLevel  DistancePMJ  MEAN(area)          STD(area)  MEAN(angle_AP)        STD(angle_AP)  MEAN(angle_RL)        STD(angle_RL)  MEAN(diameter_AP)   STD(diameter_AP)  MEAN(diameter_RL)   STD(diameter_RL)  MEAN(eccentricity)  STD(eccentricity)  MEAN(orientation)      STD(orientation)  MEAN(solidity)      STD(solidity)  SUM(length)
"2022-12-06 16:57:33"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "0"           ""         ""           70.18783267281653   0.0        2.759028956254652     0.0            13.426794943347216    0.0            7.642569740858666   0.0               11.967398081968513  0.0               0.7695257203552127  0.0                1.1073798178329701     0.0               0.9349333333333333  0.0            1.029293815567324
"2022-12-06 16:57:33"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "1"           ""         ""           65.19992482576312   0.0        2.6477986592570417    0.0            12.883732671268943    0.0            7.170174386686721   0.0               11.479623207575598  0.0               0.7809447173833011  0.0                0.7045383853767712     0.0               0.9698067632850241  0.0            1.0269219965887146
"2022-12-06 16:57:33"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "2"           ""         ""           70.22576319741323   0.0        2.537018432048123     0.0            12.348825437503878    0.0            7.148318898029008   0.0               12.49561727012578   0.0               0.8202075286909986  0.0                1.1240025749714158     0.0               0.9505766062602965  0.0            1.0246886525761207
"2022-12-06 16:57:33"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "3"           ""         ""           78.19599464586159   0.0        2.426689344688916     0.0            11.822284083960552    0.0            7.954349988531708   0.0               12.730726861984742  0.0               0.7807727767905489  0.0                1.2093578737104327     0.0               0.9379210779595765  0.0            1.0225889719256869
"2022-12-06 16:57:33"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "4"           ""         ""           78.353136008265     0.0        2.3168124461816393    0.0            11.304309757684244    0.0            7.946072975165864   0.0               12.541402135108942  0.0               0.7736712141532227  0.0                2.1584089371752406     0.0               0.9643931795386158  0.0            1.0206181700087171
"2022-12-06 16:57:33"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "5"           ""         ""           69.66912356400812   0.0        2.207388764620656     0.0            10.795093920692352    0.0            7.607982594325332   0.0               11.540335239780907  0.0               0.7519225640663295  0.0                2.1472797542328954     0.0               0.9535274356103024  0.0            1.0187714949511624
"2022-12-06 16:57:33"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "6"           ""         ""           58.97866358135752   0.0        2.0984193073453348    0.0            10.294818396146836    0.0            6.796746946277823   0.0               10.961380529488535  0.0               0.7845519899944505  0.0                6.1401428478231255     0.0               0.9771505376344086  0.0            1.0170442332212148
"2022-12-06 16:57:33"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "7"           ""         ""           63.998100991736116  0.0        1.9899050610947115    0.0            9.803655448854935     0.0            6.873621979738639   0.0               11.69341184837346   0.0               0.8089917085851158  0.0                7.780333804228145      0.0               0.9653679653679653  0.0            1.0154317150131558
"2022-12-06 16:57:33"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "8"           ""         ""           66.06770327491503   0.0        1.8818469921639238    0.0            9.321767897957992     0.0            7.167783959202665   0.0               11.513586461271025  0.0               0.7825799773594331  0.0                7.08900654760444       0.0               0.9827692307692307  0.0            1.0139293194174932
...
```

To have the `VertLevel` column filled, I have to use the `-vert` flag and provide a range covering all available levels, e.g.:

```
sct_process_segmentation -i t1w_seg-manual.nii.gz -perslice 1 -vertfile t1w_seg-manual_labeled.nii.gz -vert 1:20
```

The output then looks like this (i.e., `VertLevel` column is filled):

```
Timestamp          SCT Version                                             Filename                                                                              Slice (I->S)  VertLevel  DistancePMJ  MEAN(area)          STD(area)  MEAN(angle_AP)        STD(angle_AP)  MEAN(angle_RL)        STD(angle_RL)  MEAN(diameter_AP)   STD(diameter_AP)  MEAN(diameter_RL)   STD(diameter_RL)  MEAN(eccentricity)  STD(eccentricity)  MEAN(orientation)      STD(orientation)  MEAN(solidity)      STD(solidity)  SUM(length)
"2022-12-06 17:05:44"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "0"           "6"        ""           70.18783267281653   0.0        2.759028956254652     0.0            13.426794943347216    0.0            7.642569740858666   0.0               11.967398081968513  0.0               0.7695257203552127  0.0                1.1073798178329701     0.0               0.9349333333333333  0.0            1.029293815567324
"2022-12-06 17:05:44"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "1"           "6"        ""           65.19992482576312   0.0        2.6477986592570417    0.0            12.883732671268943    0.0            7.170174386686721   0.0               11.479623207575598  0.0               0.7809447173833011  0.0                0.7045383853767712     0.0               0.9698067632850241  0.0            1.0269219965887146
"2022-12-06 17:05:44"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "2"           "6"        ""           70.22576319741323   0.0        2.537018432048123     0.0            12.348825437503878    0.0            7.148318898029008   0.0               12.49561727012578   0.0               0.8202075286909986  0.0                1.1240025749714158     0.0               0.9505766062602965  0.0            1.0246886525761207
"2022-12-06 17:05:44"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "3"           "5"        ""           78.19599464586159   0.0        2.426689344688916     0.0            11.822284083960552    0.0            7.954349988531708   0.0               12.730726861984742  0.0               0.7807727767905489  0.0                1.2093578737104327     0.0               0.9379210779595765  0.0            1.0225889719256869
"2022-12-06 17:05:44"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "4"           "5"        ""           78.353136008265     0.0        2.3168124461816393    0.0            11.304309757684244    0.0            7.946072975165864   0.0               12.541402135108942  0.0               0.7736712141532227  0.0                2.1584089371752406     0.0               0.9643931795386158  0.0            1.0206181700087171
"2022-12-06 17:05:44"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "5"           "5"        ""           69.66912356400812   0.0        2.207388764620656     0.0            10.795093920692352    0.0            7.607982594325332   0.0               11.540335239780907  0.0               0.7519225640663295  0.0                2.1472797542328954     0.0               0.9535274356103024  0.0            1.0187714949511624
"2022-12-06 17:05:44"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "6"           "5"        ""           58.97866358135752   0.0        2.0984193073453348    0.0            10.294818396146836    0.0            6.796746946277823   0.0               10.961380529488535  0.0               0.7845519899944505  0.0                6.1401428478231255     0.0               0.9771505376344086  0.0            1.0170442332212148
"2022-12-06 17:05:44"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "7"           "5"        ""           63.998100991736116  0.0        1.9899050610947115    0.0            9.803655448854935     0.0            6.873621979738639   0.0               11.69341184837346   0.0               0.8089917085851158  0.0                7.780333804228145      0.0               0.9653679653679653  0.0            1.0154317150131558
"2022-12-06 17:05:44"  "git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*"  "/Users/valosek/Desktop/process_seg_issue/sct_testing_data/t1/t1w_seg-manual.nii.gz"  "8"           "5"        ""           66.06770327491503   0.0        1.8818469921639238    0.0            9.321767897957992     0.0            7.167783959202665   0.0               11.513586461271025  0.0               0.7825799773594331  0.0                7.08900654760444       0.0               0.9827692307692307  0.0            1.0139293194174932
...
```

### Steps to Reproduce

```
# download example data
sct_download_data -d sct_testing_data -o sct_testing_data
cd sct_testing_data/t1

# do labeling
sct_label_vertebrae -i t1w.nii.gz -s t1w_seg-manual.nii.gz -c t1 $(cat init_label_vertebrae.txt) 

# run sct_process_segmentation
sct_process_segmentation -i t1w_seg-manual.nii.gz -perslice 1 -vertfile t1w_seg-manual_labeled.nii.gz
```

**Comment by valosekj** [comment] 2022-12-07 03:20
A quick fix could be to set the default value for the `vert` flag as proposed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/a390776b25c28d7af6ab8b986282012631bd3fa1:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a390776b25c28d7af6ab8b986282012631bd3fa1/spinalcordtoolbox/scripts/sct_process_segmentation.py#L150-L155

But I have to explore this solution in more details.

**Comment by joshuacwnewton** [comment] 2023-01-13 22:49
Ah! This issue is a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3113, so I'm going to close it.

There is [some investigation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3113#issuecomment-748633121) in that issue suggesting a potential quick solution inside of `aggregate_per_slice_or_level`. It might be worthwhile to follow up with the suggestion there.

**Closed by joshuacwnewton** 2023-01-13 22:49 UTC
