### ISSUE TITLE
pytest issue `assert not changed` and how to run in IDE

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4468] opened 2024-05-03 20:34 UTC
this is not related to a bug in sct, but rather, i'm struggling to write a proper test

related to #4467 i'm trying to write an additional test in the cli for sct_extract_metric, i'm replicating the test above, adding a condition: 
```python

@pytest.mark.sct_testing
@pytest.mark.usefixtures("run_in_sct_testing_data_dir")
def test_sct_extract_metric_against_groundtruth():
    """Verify that computed values are equivalent to known ground truth values."""
    fname_out = 'quantif_mtr.csv'
    sct_extract_metric.main(argv=['-i', 'mt/mtr.nii.gz', '-f', 'mt/label/atlas', '-method', 'wa', '-l', '51',
                                  '-z', '1:2', '-o', fname_out])
    results = np.genfromtxt(fname_out, skip_header=1, delimiter=',')
    results = results[~np.isnan(results)]  # Remove non-numeric fields such as filename, SCT version, etc.
    assert results == pytest.approx([176.1532, 32.6404, 11.4573], abs=0.001)  # Size[vox], WA, and STD respectively


# @pytest.mark.sct_testing
@pytest.mark.usefixtures("run_in_sct_testing_data_dir")
def test_sct_extract_metric_using_combined_labels():
    """Verify that using CombinedLabels with flag combine=1 does not produce an error."""
    fname_out = 'quantif_mtr2.csv'
    sct_extract_metric.main(argv=['-i', 'mt/mtr.nii.gz', '-f', 'mt/label/atlas', '-method', 'wa', '-l', '51',
                                  '-z', '1:2', '-combine', '0', '-o', fname_out])
    results = np.genfromtxt(fname_out, skip_header=1, delimiter=',')
    results = results[~np.isnan(results)]  # Remove non-numeric fields such as filename, SCT version, etc.
    assert results == pytest.approx([176.1532, 32.6404, 11.4573], abs=0.001)  # Size[vox], WA, and STD respectively
```

however when running the test, the 2nd bloc fails (whereas it should not)
```console
(venv_sct) julien-macbook:~/code/spinalcordtoolbox $ pytest testing/cli/test_cli_sct_extract_metric.py 
============================================================================= test session starts ==============================================================================
platform darwin -- Python 3.9.19, pytest-8.1.1, pluggy-1.4.0 -- /Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/bin/python
cachedir: .pytest_cache
rootdir: /Users/julien/code/spinalcordtoolbox
configfile: setup.cfg
plugins: cov-5.0.0, console-scripts-1.4.1
collected 2 items                                                                                                                                                              

testing/cli/test_cli_sct_extract_metric.py::test_sct_extract_metric_against_groundtruth PASSED                                                                           [ 50%]
testing/cli/test_cli_sct_extract_metric.py::test_sct_extract_metric_using_combined_labels PASSED                                                                         [100%]
testing/cli/test_cli_sct_extract_metric.py::test_sct_extract_metric_using_combined_labels ERROR                                                                          [100%]

==================================================================================== ERRORS ====================================================================================
______________________________________________________ ERROR at teardown of test_sct_extract_metric_using_combined_labels ______________________________________________________
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/runner.py", line 340, in from_call
    result: Optional[TResult] = func()
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/runner.py", line 240, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/threadexception.py", line 92, in pytest_runtest_teardown
    yield from thread_exception_runtest_hook()
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/threadexception.py", line 63, in thread_exception_runtest_hook
    yield
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 95, in pytest_runtest_teardown
    yield from unraisable_exception_runtest_hook()
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 65, in unraisable_exception_runtest_hook
    yield
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/logging.py", line 856, in pytest_runtest_teardown
    yield from self._runtest_for(item, "teardown")
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/logging.py", line 832, in _runtest_for
    yield
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/capture.py", line 888, in pytest_runtest_teardown
    return (yield)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/runner.py", line 187, in pytest_runtest_teardown
    item.session._setupstate.teardown_exact(nextitem)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/runner.py", line 555, in teardown_exact
    raise exceptions[0]
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/runner.py", line 544, in teardown_exact
    fin()
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/fixtures.py", line 1046, in finish
    raise exceptions[0]
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/_pytest/fixtures.py", line 1035, in finish
    fin()
  File "/Users/julien/code/spinalcordtoolbox/testing/conftest.py", line 55, in <lambda>
    request.addfinalizer(lambda: check_testing_data_integrity(files_checksums))
  File "/Users/julien/code/spinalcordtoolbox/testing/conftest.py", line 90, in check_testing_data_integrity
    assert not changed
AssertionError: assert not [('/Users/julien/code/spinalcordtoolbox/data/sct_testing_data/quantif_mtr2.csv', '93c129a45fc8431da034060f754d3f93'), ('/Users/julien/code/spinalcordtoolbox/data/sct_testing_data/quantif_mtr.csv', '93c129a45fc8431da034060f754d3f93')]
=========================================================================== short test summary info ============================================================================
ERROR testing/cli/test_cli_sct_extract_metric.py::test_sct_extract_metric_using_combined_labels - AssertionError: assert not [('/Users/julien/code/spinalcordtoolbox/data/sct_testing_data/quantif_mtr2.csv', '93c129a45fc8431da034060f754d3f93'), ('/Users/julien/code/spina...
========================================================================== 2 passed, 1 error in 1.25s ==========================================================================
(venv_sct) julien-macbook:~/code/spinalcordtoolbox $ 
```

is this because the assert has the exact same result as the previous test?

sorry i don't have time to dig-- so i'm just throwing this out there

on a related note: how does one run the pytest suite in an IDE? i'm using vscode-- should it go through the launch.json? ( i tried-- didn't work-- got an error: cannot import numpy, which is strange-- again, no time to dig unfortunateyl)

**Comment by joshuacwnewton** [comment] 2024-05-03 20:41
This bug has nothing to do with your test. It is actually a long-standing issue with the "test data integrity check" implemented by Drulex:

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2911

Basically, there is a check to make sure that the files in the `sct_testing_data` folder don't get modified by the tests (so that we can be sure every test run is done on clean data). However, many of our tests are actually outputting to the test directory, meaning that the `sct_testing_data` folder does not stay "clean".

This causes a failure if tests are not run on a "fresh" copy of `sct_testing_data`. However, it's not a test failure, it's just an "error". So, you will see that your tests actually passed.

(This is one of those small annoyances that I've gotten used to, but if it's bothersome enough, I can spend a little time fixing things so that we keep a "fresh" copy of the test data every time.)

**Comment by jcohenadad** [comment] 2024-05-03 21:04
thank you for the explanation @joshuacwnewton !

**Comment by joshuacwnewton** [comment] 2024-05-06 17:34
Closing this issue as a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2911, but I will follow up in that issue so that we don't get these errors anymore. :)

**Closed by joshuacwnewton** 2024-05-06 17:34 UTC
