### ISSUE TITLE
sct_testing returns error code 0 when passed a non-existing function as argument

### ISSUE THREAD

**Issue by Drulex** [spinalcordtoolbox/spinalcordtoolbox#3183] opened 2021-01-20 15:58 UTC
### Description

<Description of the issue>

### Steps to Reproduce
```
$  sct_testing --function hello_i_dont_exist

--
Spinal Cord Toolbox (git-aj/2912-revert-sct_concat_transfo-2d59a731d45fd2c9608049f11bf76eb1bae1f7c4)

sct_testing --function hello_i_dont_exist
--

Creating temporary folder (/tmp/sct-20210120104748.986537-3zit34i4)
Command-line usage error: Function "hello_i_dont_exist" is not part of the list of testing functions
Will run through the following tests:
status: []
Finished! Elapsed time: 0s

$  echo $?
0

```
**Expected behavior:** <What you expect to happen>
This should return a non-zero error code. The `pytest` functional test wrappers rely on the error code returned to assess the success/failure of a functional test.

**Comment by joshuacwnewton** [comment] 2021-01-20 18:58
I wrote a test that checks for non-zero error codes (which you noticed) in #3156.

The problem is, I only checked for usage with no args (i.e. `sct_testing` without any additional arguments). I didn't check for other faulty usage... so, perhaps another test should be added in `test_cli.py`. :)

**Comment by joshuacwnewton** [comment] 2023-01-13 22:12
`sct_testing` no longer exists. Closing as resolved.

**Closed by joshuacwnewton** 2023-01-13 22:12 UTC
Labels: bug, sct_testing, good first issue
