### ISSUE TITLE
Discrepancy between sct_qc and centerline results

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2813] opened 2020-07-23 14:39 UTC
Version: SCT dfd51cd39921a592f062b326a1d680e43b8ca5e0
Data: sct_testing_data/t2

When running:
~~~
sct_get_centerline -i t2.nii.gz -c t2
~~~
I obtain a correct centerline, with only **one** pixel per axial slice. Example here for the most inferior slice:

![Screen Shot 2020-07-23 at 10 36 23 AM](https://user-images.githubusercontent.com/2482071/88299599-88e20880-ccd0-11ea-9eb7-aa35d77d9cfc.png)

Now, the problem is that, while working on https://github.com/neuropoly/spinalcordtoolbox/pull/2734, I was debugging `sct_qc` with `sct_get_centerline` option, and came across the fact that, when inputting the centerline as output by the command above, the routine that is supposed to find the centerline `reports.slice._axial_center()` finds **two** pixels in some slices, including the most inferior one:
````python
data[0, 50, 40:45]
array([0, 1, 1, 0, 0])
````

There might be something going on, with the re-orientation of the data. Something to watch out for.

**Comment by jcohenadad** [comment] 2020-07-23 16:12
I might have found the culprit:
https://github.com/neuropoly/spinalcordtoolbox/blob/6888ea028159024d9a6f5f674463ab366825f880/spinalcordtoolbox/reports/slice.py#L58

**Comment by jcohenadad** [comment] 2020-08-24 22:56
> Does `_resample_slicewise` write to disk or is that happening elsewhere?

it does not write to disk-- i generate the nifti file via the debugger (with a `nibabel.save()`)

**Comment by cfhammill** [comment] 2020-08-25 00:29
Ahh I misunderstood the title of the issue, I thought that the issue was that the QC was modifying the test data on disk. Instead this is a discrepancy between running manual and automatic QC of the result centerline.

**Comment by jcohenadad** [comment] 2020-08-25 01:45
@cfhammill sorry, my description of the issue was obscure. I've updated the title, and here are some clarifications: the problem is that the QC report does not provide an accurate representation of the results, because during the QC preparation routine (which involves image resampling), the _true_ centerline is slightly displaced.

**Comment by joshuacwnewton** [comment] 2023-01-21 19:59
Closing this issue as a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3625.

Both issues identify problematic resampling in the QC reports for single-voxel centerline images.

**Closed by joshuacwnewton** 2023-01-21 19:59 UTC
