### ISSUE TITLE
Some scripts don't raise exceptions when sanity check errors are encountered

### ISSUE THREAD

**Issue by Drulex** [spinalcordtoolbox/spinalcordtoolbox#3188] opened 2021-01-21 15:51 UTC
### Description

I noticed that some scripts perform checks on usage and other sanity checks, but when handling the error case they fail to raise an exception and simply log the error and continue processing. Without explicit mention that the error is voluntarily ignored and that processing should continue this is confusing.

### Steps to Reproduce

Possibly non-exhaustive list of offending scripts:

```
$  git --no-pager grep -A1 -B1 -e 'printv(parser.error' --or -e 'printv("ERROR' ./spinalcordtoolbox/scripts/
spinalcordtoolbox/scripts/sct_analyze_lesion.py-            else:
spinalcordtoolbox/scripts/sct_analyze_lesion.py:                printv("ERROR input file %s is not binary file with 0 and 1 values" % fname_mask, 1, 'error')
spinalcordtoolbox/scripts/sct_analyze_lesion.py-
--
spinalcordtoolbox/scripts/sct_analyze_lesion.py-    #     path_template = None
spinalcordtoolbox/scripts/sct_analyze_lesion.py:    #     printv("ERROR output directory %s is not a valid directory" % path_template, 1, 'error')
spinalcordtoolbox/scripts/sct_analyze_lesion.py-
--
spinalcordtoolbox/scripts/sct_analyze_lesion.py-    # if not os.path.isdir(path_results) and os.path.exists(path_results):
spinalcordtoolbox/scripts/sct_analyze_lesion.py:    #     printv("ERROR output directory %s is not a valid directory" % path_results, 1, 'error')
spinalcordtoolbox/scripts/sct_analyze_lesion.py-    if not os.path.exists(path_results):
--
spinalcordtoolbox/scripts/sct_analyze_texture.py-    if not os.path.isdir(param.path_results) and os.path.exists(param.path_results):
spinalcordtoolbox/scripts/sct_analyze_texture.py:        printv("ERROR output directory %s is not a valid directory" % param.path_results, 1, 'error')
spinalcordtoolbox/scripts/sct_analyze_texture.py-    if not os.path.exists(param.path_results):
--
spinalcordtoolbox/scripts/sct_create_mask.py-        if param.process[0] not in param.process_list:
spinalcordtoolbox/scripts/sct_create_mask.py:            printv(parser.error('ERROR: Process ' + param.process[0] + ' is not recognized.'))
spinalcordtoolbox/scripts/sct_create_mask.py-    if arguments.size is not None:
--
spinalcordtoolbox/scripts/sct_detect_pmj.py-        if not os.path.isdir(path_results) and os.path.exists(path_results):
spinalcordtoolbox/scripts/sct_detect_pmj.py:            printv("ERROR output directory %s is not a valid directory" % path_results, 1, 'error')
spinalcordtoolbox/scripts/sct_detect_pmj.py-        if not os.path.exists(path_results):
--
spinalcordtoolbox/scripts/sct_get_centerline.py-    else:
spinalcordtoolbox/scripts/sct_get_centerline.py:        printv("ERROR: The selected method is not available: {}. Please look at the help.".format(method), type='error')
spinalcordtoolbox/scripts/sct_get_centerline.py-        return
--
spinalcordtoolbox/scripts/sct_image.py-        if n_in != 1:
spinalcordtoolbox/scripts/sct_image.py:            printv(parser.error('ERROR: -mcs need only one input'))
spinalcordtoolbox/scripts/sct_image.py-        if len(im_in.data.shape) != 5:
spinalcordtoolbox/scripts/sct_image.py:            printv(parser.error('ERROR: -mcs input need to be a multi-component image'))
spinalcordtoolbox/scripts/sct_image.py-        im_out = multicomponent_split(im_in)
--
spinalcordtoolbox/scripts/sct_image.py-            if im.data.shape != im_ref.data.shape:
spinalcordtoolbox/scripts/sct_image.py:                printv(parser.error('ERROR: -omc inputs need to have all the same shapes'))
spinalcordtoolbox/scripts/sct_image.py-            del im
--
spinalcordtoolbox/scripts/sct_image.py-        if len(space_files) > 2 or len(space_files) < 1:
spinalcordtoolbox/scripts/sct_image.py:            printv(parser.error('ERROR: -to-fsl expects 1 or 2 arguments'))
spinalcordtoolbox/scripts/sct_image.py-            return
--
spinalcordtoolbox/scripts/sct_image.py-        im_out = None
spinalcordtoolbox/scripts/sct_image.py:        printv(parser.error('ERROR: you need to specify an operation to do on the input image'))
spinalcordtoolbox/scripts/sct_image.py-
--
spinalcordtoolbox/scripts/sct_maths.py-        elif len(sigmas) != len(data.shape):
spinalcordtoolbox/scripts/sct_maths.py:            printv(parser.error('ERROR: -laplacian need the same number of inputs as the number of image dimension OR only one input'))
spinalcordtoolbox/scripts/sct_maths.py-        # adjust sigma based on voxel size
--
spinalcordtoolbox/scripts/sct_maths.py-        elif len(sigmas) != len(data.shape):
spinalcordtoolbox/scripts/sct_maths.py:            printv(parser.error('ERROR: -smooth need the same number of inputs as the number of image dimension OR only one input'))
spinalcordtoolbox/scripts/sct_maths.py-        # adjust sigma based on voxel size
--
spinalcordtoolbox/scripts/sct_maths.py-        if arguments.shape in ['disk', 'square'] and arguments.dim is None:
spinalcordtoolbox/scripts/sct_maths.py:            printv(parser.error('ERROR: -dim is required for -dilate with 2D morphological kernel'))
spinalcordtoolbox/scripts/sct_maths.py-        data_out = sct_math.dilate(data, size=arguments.dilate, shape=arguments.shape, dim=arguments.dim)
--
spinalcordtoolbox/scripts/sct_maths.py-        if arguments.shape in ['disk', 'square'] and arguments.dim is None:
spinalcordtoolbox/scripts/sct_maths.py:            printv(parser.error('ERROR: -dim is required for -erode with 2D morphological kernel'))
spinalcordtoolbox/scripts/sct_maths.py-        data_out = sct_math.erode(data, size=arguments.erode, shape=arguments.shape, dim=arguments.dim)
--
spinalcordtoolbox/scripts/sct_maths.py-        data_out = None
spinalcordtoolbox/scripts/sct_maths.py:        printv(parser.error('ERROR: you need to specify an operation to do on the input image'))
spinalcordtoolbox/scripts/sct_maths.py-
--
spinalcordtoolbox/scripts/sct_resample.py-    else:
spinalcordtoolbox/scripts/sct_resample.py:        printv(parser.error('ERROR: you need to specify one of those three arguments : -f, -mm or -vox'))
spinalcordtoolbox/scripts/sct_resample.py-
spinalcordtoolbox/scripts/sct_resample.py-    if arg > 1:
spinalcordtoolbox/scripts/sct_resample.py:        printv(parser.error('ERROR: you need to specify ONLY one of those three arguments : -f, -mm or -vox'))
spinalcordtoolbox/scripts/sct_resample.py-
```

Note: some of scripts above perform an action after logging the error, in that case a comment or trace documenting the behavior (if correct) is most welcome.

**Expected behavior:** <What you expect to happen>
When an error is detected, the script should raise the appropriate exception. It may also return a specific error code depending on the exception.

**Actual behavior:** <What actually happens>
Script prints the error to the screen, but continues the processing. This is problematic if a lot of content is printed to the screen and the user does not see the error message.

Note: It is possible that the error is somehow handled internally by the script later on (haven't checked every single on of them), but it is still a bad idea as it is not intuitive what happens when the error is detected.

**Comment by joshuacwnewton** [comment] 2021-01-21 16:21
@Drulex Does this also affect scripts that use `logger.error` instead of raising an exception? IIRC, logger.error doesn't halt execution, but I've seen it used without raising an exception in a few places.

**Comment by Drulex** [comment] 2021-01-21 16:37
> @Drulex Does this also affect scripts that use `logger.error` instead of raising an exception? IIRC, logger.error doesn't halt execution, but I've seen it used without raising an exception in a few places.

Yes same logic applies. If there is a reason to log the error without halting the program it should be very explicit, otherwise chances are it could be converted to a warning.

**Comment by joshuacwnewton** [comment] 2023-01-13 22:11
This issue is a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3861, which was fixed by https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3874.

**Closed by joshuacwnewton** 2023-01-13 22:11 UTC
Labels: bug
