### ISSUE TITLE
Source .bashrc if user is running a login shell

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2622] opened 2020-03-01 02:04 UTC
When a "login shell" starts up, it reads the file `/etc/profile` and then `~/.bash_profile` or `~/.bash_login` or `~/.profile` (whichever one exists - it only reads one of these, checking for them in the order mentioned).

When a "non-login shell" starts up, it reads the file `/etc/bashrc` and then the file `~/.bashrc`.

SCT's environment variables are declared in `.bashrc` (for bash shells), which can cause problems if users are running a login shell without having a `.bash_profile` or `.bash_login` or `.profile` that sources the `.bashrc`. 

We might want to address that scenario.

Source: http://hayne.net/MacDev/Notes/unixFAQ.html#shellStartup

**Comment by kousu** [comment] 2020-03-19 17:36
I was looking at this and thinking I didn't like that the installer edits my environment for me. There's lots of reasons:

- this one, that there's this old Unix cruft of login vs non-login shells
- I'm not necessarily using `bash`
- different distros decide whether or not to source things in order

Trying to get user-local customizations set up is always a pain. I was hoping we could talk about this, but fixing it more conventionally might be invasive.

Some strategies:

* Install directly to /usr/bin or /usr/local/bin; this is system-wide and the right choice depends on the particular OS
* Install to /opt/spinalcordtoolbox and add the right lines to a file in `/etc/profile.d/`. This is also systemwide and only appropriate for some OSes.
* [`~/.local/bin/`](https://specifications.freedesktop.org/basedir-spec/latest/) is a common place for user-local customizations; this is where python programs installed with `pip install --user` go. [Not all OS](https://unix.stackexchange.com/questions/316765/which-distributions-have-home-local-bin-in-path/392710#392710) come preconfigured to use this, so we would need to have the user edit their `.profile` (or equivalent) to add `export PATH=~/.local/bin:$PATH` one time.

I think there is wisdom in this short essay: [Drew DeVault. "Developers shouldn't distribute their own software." Published 2019-12-09](https://drewdevault.com/2019/12/09/Developers-shouldnt-distribute.html).

**Comment by kousu** [comment] 2020-03-19 17:52
In general I would advocate for Drew's view, making sure the software runs on its own and also making sure it can be packaged cleanly by clearly documenting what dependencies we have and respecting environment variables. Trying to guess OS-specific customizations is a sisyphean battle; it's better to work with the OS's packaging community, if we can.

The biggest stumbling block to this is that we're "vendoring" https://github.com/ANTsX/ANTs in with [`compile_ants.py`](https://github.com/neuropoly/spinalcordtoolbox/blob/master/install/compile_ants.py). ANTS would have to be packaged for each OS independently, and then our OS-level package could depend on it. When running from source we would need to make sure there are good instructions on how to install ANTS manually; I think we could probably help them out by writing those instructions and pointing our users who want to compile from source there; it seems perhaps they haven't been updated for users in [8 years](https://brianavants.wordpress.com/2012/04/13/updated-ants-compile-instructions-april-12-2012/).

For "app" situations, where researchers just want to be able to use the software but don't need it as readily available from their daily workstation, we could continue to build Docker images where we vendor and configure exactly what we need. But in that case we needn't worry about `.bashrc`.

**Comment by jcohenadad** [comment] 2020-03-19 18:22
Regarding strategy to install directly to /usr/bin or /usr/local/bin: I can anticipate issues when researchers are using computer clusters from institutions, where they would need sudo power to write on /usr/bin.  Current SCT's installation make it convenient for everyone to install it in their home (or under /usr/bin if they decide to do so). I guess the same argument applies to the installation to `/opt/spinalcordtoolbox`?

Regarding the strategy to install in `~/.local/bin/`, this prevents the issue stated above, but then users would still need to edit their environment variable.

The article from Drew DeVault was an interesting read. The only issue I have with that essay was the following expectation from users: "And to users: install packages from your distro’s repositories, and learn how its packaging process works so you can get involved when you find a package missing". This, of course, can be relevant depending on the context, but in our case, SCT is used by clinicians and non-computer savvy, so we cannot and should not expect them to be familiar with packaging procedures. 

We've had long discussions about how to have the installation work for everyone in every situations. For the past few years, I can say that despite the few glitches (which made us iteratively improve `install_sct` by adding "cases"), so far most people, from a wide spectrum of computer skills, were able to properly install SCT. 

Regarding ANTs: as you probably noticed, we only created binaries for CentOS6, other Linux distros and OSX. So far, we didn't have any user complains. So, would it be realistic to find a solution "in the middle" and do what you suggest (work with OS packaging) while shipping OS-specific binaries when needed?

About Docker: I see a few limitations in "imposing" it for most of our users (i.e. making it the default installation). 1) Some institutions don't allow Docker, 2) Some users (including me ;-) ) find it less convenient to have to start Docker, start the interactive container, before being able to call SCT, 3) Some users will be confused with folder shared.

**Comment by kousu** [comment] 2020-03-24 18:32
On the more immediate issue:

- many distros come with 

```
# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi
```

in their ~/.bash_profile, precisely to make sure this works. What's more, `install_sct` *adds this* here:

https://github.com/neuropoly/spinalcordtoolbox/blob/266bfc88d6eb6e96a2c2f1ec88c2e185c6f88e09/install_sct#L221-L242

if it doesn't already exist. It uses a heuristic to detect if it needs to do this but it should be good for 99% of the time.

**Comment by kousu** [comment] 2020-03-24 18:36
The trickier issue is how to handle non-login shells, for example those run by:

i. `cron`/`at`
ii. `ssh` when run like `ssh server.example.com -- isct_antsRegistration ...`

On *some* distros (e.g. Ubuntu Xenial) the latter will work, but on others it will not. I'm not sure where the configuration difference is yet. A workaround is for remote users to prefix the command with `sh -l` which forces a login shell: `ssh server.example.com -- 'sh -l "isct_antsRegistration ..."'`, though that can get messy depending on how many nested quotes are needed.

**Comment by jcohenadad** [comment] 2020-03-24 18:45
For a bit of context, this issue was partly motivated by SCT's installation using windows subsystem, which could not properly source the created `.bashrc`, see [this post](https://github.com/neuropoly/sct_docker/pull/52#pullrequestreview-377169912). As you said 99% of our users don't have bashrc source problems, so maybe we can lower the scope of this issue and only address this windows subsystem installation case?

**Comment by kousu** [comment] 2020-03-24 19:12
It looks like the installer does support ~/.profile already, right [here](https://github.com/neuropoly/spinalcordtoolbox/issues/2622#L229). Has it actually failed on WSL?

I'm sorry, I don't have a Windows environment set up yet to test this with.

I did try installing an Ubuntu 18.04 container like the WSL instructions say and it worked alright there:

```
ubuntu@sct-ubuntu-bionic:~$ echo $PATH
/home/ubuntu/spinalcordtoolbox/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

**Comment by jcohenadad** [comment] 2020-03-24 19:15
> It looks like the installer does support ~/.profile already, right here. Has it actually failed on WSL?

hum, good point. @lrouhier can you enlighten us?

**Comment by kousu** [comment] 2020-03-24 19:29
Incidentally, we're not the only ones to stumble over this. Here's brew being confounded by it: https://github.com/Linuxbrew/brew/issues/235

**Comment by lrouhier** [comment] 2020-03-24 19:29
It has not failed on WSL. because the environment does have a .bash_rc and a .profile. The reason I added it in the first place is that I was following what we did in the docker container, which exported sct_dir in the env which i interpreted as .profile. In the last version posted in the [wiki](https://github.com/neuropoly/spinalcordtoolbox/wiki/SCT-on-Windows-10:-Installation-instruction-for-SCT-on-Windows-subsytem-for-linux), I don't use it anymore because the install works.

**Comment by joshuacwnewton** [comment] 2023-01-14 17:26
This issue is, in essence, a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3149.

(They're both describing the same problem: SCT modifies `.bashrc`, but some shell configurations use `.profile`/`.bash_profile` instead..)

I'm closing this issue just to centralize discussion in a single issue.

**Closed by joshuacwnewton** 2023-01-14 17:26 UTC
Labels: installation, priority:LOW, needs-discussion
