### ISSUE TITLE
fix coherence between Image data shape and Image dim

### ISSUE THREAD

**Issue by bcdarwin** [spinalcordtoolbox/spinalcordtoolbox#2652] opened 2020-04-01 03:50 UTC
Motivation [here](https://github.com/neuropoly/spinalcordtoolbox/pull/2634/files#diff-c412321dc724aafd30df925eef9c794fR735).

In short, the following doesn't work:

```
im_out = empty_like(im)
im_out.data = np.mean(self.data, dim)  # dim is now incorrect
im_out.dim =  im_out.data.shape[:dim] + (1,) + im_out.data.shape[dim:]  # error (dim is immutable)
```

Possible solutions: add an extra shape argument to empty_like, or make dim into a property?

**Comment by jcohenadad** [comment] 2020-04-01 18:56
> make dim into a property

I would go with this, or even better, get rid of dim because it is a duplicate of the nibabel header.

**Comment by bcdarwin** [comment] 2020-04-17 01:00
So it turns out that `dim` is already a property (hence why it was immutable), and so the proposed modification to `im_out.dim` in the example above was unnecessary.  I will make a PR to delete these code comments, and we could also simplify the code as you mentioned (currently `dim` dispatches to a function `get_dimension` which is not even a method on `Image` but can handle both `Image`s and `nibabel` images.

**Closed** 2023-01-14 17:21 UTC
