### ISSUE TITLE
ValueError: Invalid coordinates in sct_label_utils viewer

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3397] opened 2021-05-19 15:41 UTC
### Description

When running `sct_label_utils`with the flag `create_viewer`to manually label a disc on SCT git-master-9a4b45715240d6c08b8d71587ffbe99a41326cc6*, the viewer opens to this slice instead of mid-saggital to show the spinal cord:
![image](https://user-images.githubusercontent.com/71230552/118840459-693a5300-b895-11eb-8508-133080acc693.png)
And the GUI closes when trying to label a disc, and ouputs on the terminal `ValueError: Invalid coordinates (226, 122, 128)` (see terminal below)

https://user-images.githubusercontent.com/71230552/118840950-d8b04280-b895-11eb-953d-9af3091e604b.mp4

### Steps to Reproduce

0. Install SCT git-master-9a4b45715240d6c08b8d71587ffbe99a41326cc6*

1. Run sct_labels_utils
```
sct_label_utils -i /mnt/x/ukbiobank_1000_labels/data_processed/sub-1069373/anat/sub-1069373_T1w.nii.gz -create-viewer 2,3,4 -o sub-1069373_T1w_labels-manual.nii.gz`
```
**Expected behavior:** 
When using SCT v5.3.0, the viewer opens to this slice:
![image](https://user-images.githubusercontent.com/71230552/118841075-fbdaf200-b895-11eb-87d2-7206b2b891ff.png)
And I am able to label the disc without any problem.
**Actual behavior:** 

``` python
(base) sabeda@DESKTOP-JQ8A4UV:/mnt/c/Users/sb199/Projet3_data$ sct_label_utils -i /mnt/x/ukbiobank_1000_labels/data_processed/sub-1069373/anat/sub-1069373_T1w.nii.gz -create-viewer 2,3,4 -o sub-1069373_T1w_labels-manual.nii.gz

--
Spinal Cord Toolbox (git-master-9a4b45715240d6c08b8d71587ffbe99a41326cc6*)

sct_label_utils -i /mnt/x/ukbiobank_1000_labels/data_processed/sub-1069373/anat/sub-1069373_T1w.nii.gz -create-viewer 2,3,4 -o sub-1069373_T1w_labels-manual.nii.gz
--

/mnt/c/Users/sb199/spinalcordtoolbox/spinalcordtoolbox/gui/widgets.py:10: MatplotlibDeprecationWarning:
The matplotlib.backends.backend_qt4agg backend was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
failed to get the current screen resources
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-sabeda'
qt.qpa.xcb: QXcbConnection: XCB error: 170 (Unknown), sequence: 175, resource id: 90, major code: 146 (Unknown), minor code: 20
Traceback (most recent call last):
  File "/mnt/c/Users/sb199/spinalcordtoolbox/spinalcordtoolbox/gui/sagittal.py", line 68, in on_select_point
    self._controller.select_point(x, y, z, label)
  File "/mnt/c/Users/sb199/spinalcordtoolbox/spinalcordtoolbox/gui/sagittal.py", line 30, in select_point
    raise ValueError('Invalid coordinates {}'.format((x, y, z)))
ValueError: Invalid coordinates (226, 122, 128)
Aborted (core dumped)
```

**Comment by joshuacwnewton** [comment] 2021-05-19 20:17
Have you encountered this with any other images? (i.e. is it a consistent problem, or is it specific to this one image?

If it's just the one image, are you able to share it? (Or if not perhaps help me access the ukbiobank dataset? I haven't tried to access it yet, so I'm not sure of the steps.)

**Comment by sandrinebedard** [comment] 2021-05-19 20:42
> Have you encountered this with any other images? (i.e. is it a consistent problem, or is it specific to this one image?

Yes I have! I tested it out on various images and the same thing occured

**Comment by joshuacwnewton** [comment] 2021-05-19 20:48
Thank you!  

I can't seem to reproduce using the images in `sct_example_data`, so it may be data-specific. Could I try and investigate using one of your images if possible? :slightly_smiling_face:

**Comment by sandrinebedard** [comment] 2021-05-19 21:08
>  Could I try and investigate using one of your images if possible? 🙂

Yes, I'll send you an image on slack since it is a private dataset

**Comment by joshuacwnewton** [comment] 2021-05-20 16:58
This is due to a very simply bug in `zeros_like` due to the changes I made in #3379. I'll open a PR asap.

Thank you so much for catching this, @sandrinebedard -- this is only a problem on `master` (so no users are experiencing this).

**Comment by joshuacwnewton** [comment] 2021-05-20 18:50
@jcohenadad Just to add a note for why this wasn't caught, currently our `spinalcordtoolbox.gui` tests are written using `unittest`, not `pytest`, so I don't believe these tests are being run right now. 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9a4b45715240d6c08b8d71587ffbe99a41326cc6/tests/test_gui.py#L77

Migrating these tests to `pytest` is on my to-do list for #3219. As soon as #3373 is merged, I would like to begin putting more focus into filling in gaps in our test suite.

**Closed** 2021-05-20 18:52 UTC
Labels: bug, sct_label_utils
