### ISSUE TITLE
`sct_download_data` fallback logic is broken

### ISSUE THREAD

**Issue by kousu** [spinalcordtoolbox/spinalcordtoolbox#3106] opened 2020-12-17 17:55 UTC
`sct_download_data` is no longer falling back to backup mirrors properly. It seems that it is reusing the HTTPS session which fails when pointed at a different session because the certs are different, of course. But that is...very weird. So this needs some investigation.

We haven't caught this because, most of the time, osf.io is fine. But if it times out (or is blocked à la Iran/China/etc) then this happens.

You can also trigger locally it by
```
sudo sh -c "echo 127.0.0.1 osf.io >> /etc/hosts"
```
(or using a firewall or DNS blocker on your router)

Here's the error:

```
$ ./install_sct
[...]
Installing binaries...


sct_download_data -d binaries_linux -o /home/kousu/src/neuropoly/spinalcordtoolbox/bin -k


--
Spinal Cord Toolbox (git-ng/strict-shell-e52c693b357067eddaebd93240a57397bf59788e*)

sct_download_data -d binaries_linux -o /home/kousu/src/neuropoly/spinalcordtoolbox/bin -k
--

Trying URL: https://osf.io/cs6zt/?action=download
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5825563e80>: Failed to establish a new connection: [Errno 111] Connection refused',)': /cs6zt/?action=download
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f58255040f0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /cs6zt/?action=download
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5825504278>: Failed to establish a new connection: [Errno 111] Connection refused',)': /cs6zt/?action=download
Link download error, trying next mirror (error was: HTTPSConnectionPool(host='osf.io', port=443): Max retries exceeded with url: /cs6zt/?action=download (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5825504400>: Failed to establish a new connection: [Errno 111] Connection refused',)))
Trying URL: https://www.neuro.polymtl.ca/_media/downloads/sct/20200801_sct_binaries_linux.tar.gz
Link download error, trying next mirror (error was: 403 Client Error: Forbidden for url: https://www.neuro.polymtl.ca/_media/downloads/sct/20200801_sct_binaries_linux.tar.gz)
Traceback (most recent call last):
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_download_data.py", line 168, in <module>
    res = main()
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_download_data.py", line 160, in main
    install_data(url, dest_folder, keep=arguments.k)
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/spinalcordtoolbox/download.py", line 145, in install_data
    tmp_file = download_data(url)
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/spinalcordtoolbox/download.py", line 81, in download_data
    raise Exception('Download error', exceptions)
Exception: ('Download error', [ConnectionError(MaxRetryError("HTTPSConnectionPool(host='osf.io', port=443): Max retries exceeded with url: /cs6zt/?action=download (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5825504400>: Failed to establish a new connection: [Errno 111] Connection refused',))",),), HTTPError('403 Client Error: Forbidden for url: https://www.neuro.polymtl.ca/_media/downloads/sct/20200801_sct_binaries_linux.tar.gz',)])

ERROR: Command failed.


Installation failed!

Please copy the historic of this Terminal (starting with the command install_sct) and paste it in a new created topic on SCT's forum:

--> http://forum.spinalcordmri.org/c/sct
```

We first saw this here: https://forum.spinalcordmri.org/t/installation-failed-at-the-end/496

**Comment by joshuacwnewton** [comment] 2022-09-30 18:41
I think I misunderstood this issue as being a Wiki-specific issue, when it's actually the fallback part that might be broken.

**Comment by joshuacwnewton** [comment] 2023-01-27 21:57
I cannot reproduce; the fallback logic looks fine to me:

```console
(master) joshua@tadpole:~/repos/spinalcordtoolbox$ sudo sh -c "echo 127.0.0.1 osf.io >> /etc/hosts"
[sudo] password for joshua: 
(master) joshua@tadpole:~/repos/spinalcordtoolbox$ sct_download_data -d course_hawaii17

--
Spinal Cord Toolbox (git-master-2d09af3ee707ca166c3d1611295a7575ffdd4cd0)

sct_download_data -d course_hawaii17
--

Trying URL: https://osf.io/6exht/?action=download
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4e2a9b1a90>: Failed to establish a new connection: [Errno 111] Connection refused')': /6exht/?action=download
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4e2a9b1ca0>: Failed to establish a new connection: [Errno 111] Connection refused')': /6exht/?action=download
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4e2a9b1e50>: Failed to establish a new connection: [Errno 111] Connection refused')': /6exht/?action=download
Link download error, trying next mirror (error was: HTTPSConnectionPool(host='osf.io', port=443): Max retries exceeded with url: /6exht/?action=download (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4e2a929040>: Failed to establish a new connection: [Errno 111] Connection refused')))
Trying URL: https://github.com/spinalcordtoolbox/sct_tutorial_data/releases/download/SCT-Course/hawaii17.zip
Downloading: hawaii17.zip
Status: 100%|█████████████████████████████████████████████████████| 230M/230M [00:04<00:00, 52.7MB/s]
Creating temporary folder (/tmp/sct_2023-01-27_16-49-33_install-data_bg9dstof)
Unzip data to: /tmp/sct_2023-01-27_16-49-33_install-data_bg9dstof
Copying data to: /home/joshua/repos/spinalcordtoolbox/data/course_hawaii17
Removing temporary folders...
Done!
```

Looking at the error log in @kousu's post, I think what happened was that _both_ available links failed for the user:

> ```
> Trying URL: https://osf.io/cs6zt/?action=download
> Link download error, trying next mirror (error was: HTTPSConnectionPool(host='osf.io', port=443): Max retries exceeded with url: /cs6zt/?action=download (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5825504400>: Failed to establish a new connection: [Errno 111] Connection refused',)))
> Trying URL: https://www.neuro.polymtl.ca/_media/downloads/sct/20200801_sct_binaries_linux.tar.gz
> Link download error, trying next mirror (error was: 403 Client Error: Forbidden for url: https://www.neuro.polymtl.ca/_media/downloads/sct/20200801_sct_binaries_linux.tar.gz)
> ```

Having exhausted all URLs, the `for; else:` block threw an exception:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2d09af3ee707ca166c3d1611295a7575ffdd4cd0/spinalcordtoolbox/download.py#L180

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2d09af3ee707ca166c3d1611295a7575ffdd4cd0/spinalcordtoolbox/download.py#L221-L222

Which we see in the traceback:

> ```python
>   File "/home/kousu/src/neuropoly/spinalcordtoolbox/spinalcordtoolbox/download.py", line 81, in download_data
>    raise Exception('Download error', exceptions)
> Exception: ('Download error', [ConnectionError(MaxRetryError("HTTPSConnectionPool(host='osf.io', port=443): Max retries exceeded with url: /cs6zt/?action=download (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5825504400>: Failed to establish a new connection: [Errno 111] Connection refused',))",),), HTTPError('403 Client Error: Forbidden for url: https://www.neuro.polymtl.ca/_media/downloads/sct/20200801_sct_binaries_linux.tar.gz',)])
> ```

So, I'm going to close this as non-issue, especially since we've replaced our `neuro.polymtl.ca` links with more reliable GitHub mirrors.

**Closed by joshuacwnewton** 2023-01-27 21:57 UTC
Labels: installation, user requested
