### ISSUE TITLE
Function usage requires manual refresh to appear

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3540] opened 2021-10-11 19:50 UTC
### Description

When loading the sct_plugin script in FSLeyes, the first tab (propseg) shows the usage of the function, but the other tabs don't by default. It requires manual action (eg scrolling) on the wxPython object to make the usage appear. 

https://user-images.githubusercontent.com/2482071/136847571-25e77901-5c90-4b07-8a03-eb775ed81408.mov

This is minor issue, but it could negatively impact user experience. 

### Steps to Reproduce

Tested on d83e83d with FSLeyes version 1.2.0 on macOs 10.15

**Comment by joshuacwnewton** [comment] 2021-10-12 23:34
> Hmmm... I can't seem to reproduce this on Ubuntu 20.04. I wonder if this is macOS specific... thinking

I tried running the script in my macOS 10.15 VM, and I still could not reproduce; the text descriptions load immediately without needing to scroll. :sweat_smile:

**Comment by joshuacwnewton** [comment] 2023-01-13 17:24
Closing this issue due to lack of reproducibility; feel free to reopen the issue if encountered again.

**Closed by joshuacwnewton** 2023-01-13 17:24 UTC
Labels: bug, sct_plugin.py (FSLeyes)
