### ISSUE TITLE
Error related to arrays 

### ISSUE THREAD

**Issue by YangHee-Min** [spinalcordtoolbox/spinalcordtoolbox#2338] opened 2019-07-11 18:47 UTC
### Description
It seems that there is a mishandling of the array elements of certain numpy arrays within script `sct_denoising_onlm`.

When using the command `sct_denoising_onlm -i t2/t2.nii.gz -v 2` with `sct_testing_data`, we get the following log: https://pastebin.com/hyUZtQst

After searching for a bit, it seems that the issue is related to the fact that variable `axial_middle` (that can be found [(here)](https://github.com/neuropoly/spinalcordtoolbox/blob/ffa504b8d525b393bda9d1ee1cf8f806f69f74a5/scripts/sct_denoising_onlm.py#L73)) is something other than an int array.

### Steps to Reproduce

0. Install SCT <release or git revision and platform, you can use the
   first lines of output of sct_check_dependencies>

1. Enter command `cd sct_testing_data` 

2. Enter command `sct_denoising_onlm -i t2/t2.nii.gz -v 2` 

**Expected behavior:** <What you expect to happen>
Return the denoised image and the difference between the input and the output.

**Actual behavior:** <What actually happens>
Receives error message: 
`IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
`

**Comment by YangHee-Min** [comment] 2019-07-19 14:16
@jcohenadad What should the variable type be for the variable `axial_middle` as shown[ (here)](https://github.com/neuropoly/spinalcordtoolbox/blob/4e699b3fde73d998d5a90ac81a827129e1d5acb2/scripts/sct_denoising_onlm.py#L73)? At the moment, it seems to be float but gives the error message due to being a float. Is it supposed to be an int or maybe a different type?

**Comment by jcohenadad** [comment] 2019-07-19 17:12
@YangHee-Min this function is barely used. Not a priority for now

**Comment by joshuacwnewton** [comment] 2023-01-14 18:44
This issue is a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2430, and was fixed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2432.

Running `sct_denoising_onlm -i t2/t2.nii.gz -v 2` now results in a proper matplotlib plot with no error:

![image](https://user-images.githubusercontent.com/16181459/212490800-2db25d9a-9291-43bd-80f0-c55e901d87d9.png)

**Closed by joshuacwnewton** 2023-01-14 18:44 UTC
Labels: bug, priority:LOW, sct_denoising_onlm
