### ISSUE TITLE
Migrate off nibabel's get_data()

### ISSUE THREAD

**Issue by kousu** [spinalcordtoolbox/spinalcordtoolbox#3127] opened 2020-12-25 04:08 UTC
CI is reported several warnings like

```
unit_testing/cli/test_cli_sct_label_vertebrae.py: 55 warnings
  /mnt/d/a/spinalcordtoolbox/spinalcordtoolbox/spinalcordtoolbox/image.py:350: DeprecationWarning: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).
```

We need to comb the code and update it.

**Comment by kousu** [comment] 2020-12-25 04:12
I was digging into this 6 months ago and I decided I didn't like their suggestion of `get_fdata()`. `get_fdata()` coerces data to the given type and it doesn't make it obvious that that's happening, which is expensive on large images and can cause loss of precision (because every time you resample data it gets a bit fuzzier), and avoids us pretending our data is more detailed than it might actually be. `np.asanyarray(img.dataobj)` avoids the coercion and is fast, since it's simply wrapping the pointer to the pre-existing matrix into a new `np.array`.

Apparently we're not the only ones confused by this: https://stackoverflow.com/questions/54705304/what-is-difference-between-get-data-and-get-fdata-in-nibabel-library.

**Comment by jcohenadad** [comment] 2020-12-25 19:47
I agree we should avoid changing the data type, especially if we are to rewrite the image aftwerwards, with the same dtype as input. We are often dealing with UINT8 segmentation/label data, which we don't want to manipulate as float (we can easily get into precision issue, e.g. having a label with the value 2.99999 instead of 3, see https://github.com/neuropoly/spinalcordtoolbox/issues/3101).

**Comment by joshuacwnewton** [comment] 2022-11-11 20:56
Closing this issue as it is a duplicate of:

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3854.

**Closed** 2022-11-11 20:56 UTC
Labels: maintenance
