### ISSUE TITLE
Empty log files produced by `sct_run_batch` due to non-executable script

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3030] opened 2020-11-10 20:57 UTC
When trying to run `sct_run_batch` with a script that includes trivial command (e.g., `echo`), it produces errored and empty log files.

More context in the [SCT forum issue](https://forum.spinalcordmri.org/t/minimal-correct-script-for-sct-run-batch/565).

**Comment by cfhammill** [comment] 2020-11-10 23:33
I think the issue here is that execute permissions were not set for the task file. Using the task script the user 

```bash
#!/bin/bash
## task.sh
SUBJECT=$1
echo "Hello world!"
```
without execute permissions set I get exactly the error the user reports (empty error log files). If I set execute permission the pipeline completes successfully  when I run

```bash
sct_run_batch -jobs 1 -path-data sct_course_london20/multi_subject/data/ -path-output "./" -script task.sh
```

My recommendation is we add a permissions check on the task file before initiating the batch run.

@jcohenadad can you confirm if execute permissions were set on your script file when you reproduced the bug?

**Comment by jcohenadad** [comment] 2020-11-11 00:12
thank you for finding the issue @cfhammill . 

i like the idea of copying the script and changing permission.

**Comment by joshuacwnewton** [comment] 2022-11-21 18:31
I'm reopening this issue because it is similar to an issue reported to me by @rohanbanerjee:

> I am trying to run `sct_run_batch` for my data using a bash script that I wrote (all of these files are on my temp folder in `duke`, but `duke` is being accessed via the mount point on a GRAMES workstation). The script generates blank log files. After a little digging, I found that the bash script that is getting copied in the output folder (specified using `sct_run_batch`) isn’t executable, and I’m guessing that this is the reason for the blank logs. 

After doing some digging, we found that if data files are moved off of `duke`, and the processing is done purely on the local GRAMES machine, then there is no issue.

So, somewhere in the process of copying the script on `duke`, it loses its executable status (and the aforementioned `chmod` solution that was added to SCT doesn't seem to work).

My questions:

* Why is the `chmod` command failing to make the script executable?
* Is there a more robust way of changing the permission for files?
* Should we even be doing processing directly on `duke` via the GRAMES mount point?

**Comment by joshuacwnewton** [comment] 2022-11-21 19:06
Thank you for the clarification! I wasn't aware that we are recommending against using `duke` for processing.

I can close this issue then, as it's a niche use case for a situation we don't advise in the first place. (If it comes up again in another context, we can look more deeply into this.)

**Comment by mguaypaq** [comment] 2022-11-21 19:06
My understanding (because of running into this kind of problem before) is that `duke` doesn't deal well with permissions at all. In particular, even though `chmod` runs without errors, all folder permissions are always `drwxr-xr-x` and all file permissions are always `-rw-r--r--`. Because of the way it's mounted, there's no way to give files on `duke` executable permissions.

**Closed** 2022-11-21 19:06 UTC
Labels: bug, sct_run_batch
