### ISSUE TITLE
Better identify which version of data/binary is used by SCT

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1572] opened 2018-01-16 02:23 UTC
### Description

Because we are using two mirror server, and also there is different versions of binaries/data, it would be good to encode the hash (MD5 or SHA1) of the downloaded files, so we know for sure which files were downloaded into the users machine. We would then do a printout of the version inside SCT function.

If we want to go further with checking, we can also hardcode the hashes into the source code to check if the file downloaded is really the same that the code is expecting.

**Comment by zougloub** [comment] 2018-01-18 04:40
Of course given that the data sets have many files, a single hash would have to run over the files in a deterministic order.

A short version would be:
```python
def h_tree(root):
  """ Compute an ad-hoc hash of directory contents (data + names, BFS) """
  h = hashlib.sha1()
  for cwd, dirs, files in os.walk(root):
    dirs.sort()
    files.sort()
    for filename in files:
      path = os.path.join(cwd, filename)
      relpath = os.path.relpath(path, root)
      h.update(relpath.encode("utf-8"))
      with io.open(path, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
          h.update(chunk)
  return h.hexdigest()
```

Also:

- Indicating a hash is not very helpful (only relevant to state that it's expected or unexpected), so also showing a version identifier would be a helpful addition;  
We could say that there is something that covers the concept of version in datasets (eg. PAM50 has CHANGES.md, gm_model has info.txt), but this metadata is unstructured and the code to read it would become unnecessarily complicated and error-prone.
- There would be some benefit in using something standard to also be able to verify the data integrity, eg. if the hash is distributed with the data;

As I had been facing several times such considerations about "structured data set metadata", your bug was the last straw and prompted me to take some time and do some research on this matter; to my surprise, I really couldn't find much, so yesterday evening I ended up [raising a question on datascience.stackexchange.com](https://datascience.stackexchange.com/questions/26725/rfc-data-set-metadata-standard-format) (and as a side effect, [writing supporting PoC code](https://zougloub.github.io/dsdir/) that may be of interest).

**Comment by joshuacwnewton** [comment] 2022-10-06 17:05
Closing this issue, as it's a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2489 / https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2788 / https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2959, which all mention versioning/checksums of datasets and binaries.

**Closed by joshuacwnewton** 2022-10-06 17:05 UTC
