### ISSUE TITLE
Create CLI for self2patch denoising for DWI data

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3115] opened 2020-12-20 16:18 UTC
Details of the method: https://shreyasfadnavis.medium.com/patch2self-self-supervised-denoising-via-statistical-independence-4601fda38c20

**Comment by joshuacwnewton** [comment] 2021-12-07 15:49
Duplicate of #3234.

**Comment by joshuacwnewton** [comment] 2021-12-07 15:51
Re-opening just to test this GitHub feature: https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate

**Comment by joshuacwnewton** [comment] 2021-12-07 15:51
Duplicate of #3234

**Comment by joshuacwnewton** [comment] 2021-12-07 15:52
Aha! So you have to make sure to not add a period at the end for some reason... :facepalm:

**Closed by joshuacwnewton** 2021-12-07 15:52 UTC
Labels: feature, good first issue
